### ISSUE TITLE
buffer switching unsets settings

### ISSUE THREAD

**Issue by Cutuchiqueno** [vim-pandoc/vim-pandoc#109]
Situation: I work with several buffers within one tab/window and frequently switch between them by `:bnext` or `:b FOO.md`

Problem: When I switch back to a buffer settings of pandoc are lost. For example omnifunc is unset, foldings are different (with vim-pandoc the fold is done on the header line, after buffer switching it is done below the header line, leaving the header open)

I am sure other settings are also unset, haven't tested everything

The filetype is still set to pandoc, also after switching buffers.

Question: Is it a problem of vim-pandoc or is it a problem of my local setup? (In case it is the later, is there any idea?)

**Comment by fmoralesc** [comment]
I also work like that, but I don't have that issue. Do you use a plugin manager that has lazy loading? vim-pandoc doesn't do anything on leaving/entering the buffer except managing the menu and setting virtualedit.

**Comment by fmoralesc** [comment]
Do you have any autocmd which might conflict with pandoc? Like `BufRead` events on `*.md` files, stuff like that? vim-pandoc's loading is kinda complicated for .md files.

**Comment by Cutuchiqueno** [comment]
Indeed I do something like this in my vimrc

```
:autocmd FileType python source ~/.vim/py.vim
:autocmd FileType mkd source ~/.vim/md.vim
:autocmd FileType xml source ~/.vim/xml.vim
:autocmd FileType mail source ~/.vim/mail.vim
```

to have different configuration for different filetypes. Would you say that conflicts? What would be a way to work with different configurations for each filetype that does not interfere with the way vim-pandoc works

**Comment by fmoralesc** [comment]
If the mkd filetype is used, perhaps there is a conflict there. Have you tried temporarily disabling the mkd autocmd? You can also disable markdown for vim-markdown handled files with

     g:pandoc#filetypes#pandoc_markdown = 0

**Comment by Cutuchiqueno** [comment]
Commenting out the previously states `autocmd` for mkd does in fact seem to eliminate the problem. However it raises the question which approach to add own settings for pandoc files which are not handled by vim-pandoc does not interfere with the plugin?

**Comment by fmoralesc** [comment]
It seems like you have the vim-markdown plugin installed, which is interfering with the filetype detection (`au Filetype mkd` shouldn't trigger). I guess there is some race situation going on. I'll install that plugin to test further.

You could add your custom settings to `after/ftplugin/pandoc.vim`, I think that is the most typical way to extend ftplugins.

**Comment by Cutuchiqueno** [comment]
I still had vim-markdown installed indeed though I was not aware of it since I did it before using pathogen. Nevertheless what solved the problem of unseting pandoc variables like omnifunc was not deleteing vim-markdown but rename my pandoc  markdown files to pandoc. I don't quiet understand why but using pandoc instead of md as the file extension together with the same settings as before solves all of the problems.

Thx. a lot for your quick and intensive support (like always ;-) )
