### ISSUE TITLE
Biblatex problem due to typeo

### ISSUE THREAD

**Issue by matthiasheuser** [vim-pandoc/vim-pandoc#110]
Vers. 2.0 downloaded from vim.org yesterday

autoload/pandoc.vim contains typeo line 46: "biblates" to "biblatex" 

I had error messages when trying to set default biblatex-bibliography in my vimrc. Now it works.
I guess typeo breaks the whoe implementation of Biblatex?

Thanks a lot for the plugin by the way! Very nice selection of features.

nice day

Matthias

**Comment by fmoralesc** [comment]
Thanks for the words! 

You'll see the most recent version of the plugin has a bunch more features; the vim.org version is way behind. I've forgotten to put up a new release at vim.org, so thanks for the heads up.

**Comment by fmoralesc** [comment]
A new release of the bundled plugins is available at http://www.vim.org/scripts/script.php?script_id=5088
