### ISSUE TITLE
bibliography completion word boundaries

### ISSUE THREAD

**Issue by traycerb** [vim-pandoc/vim-pandoc#111]
Using Zotero to export a collection in Bibtex format, the cite keys in the .bib file will look like:

`@article{zhang_current_2014`

However, when trying to insert a citation in the main text by typing `@` and attempting a completion, it only completes to the first underscore.  So I only get:

`@zhang`

Word boundaries are related to `iskeyword` which does typically include the underscore: `iskeyword=@,48-57,_,192-255,#`

I'm not sure this is even vim-pandoc related per se, but is there anyway to get the full citation with the autocompletion?  Manually adding the underscore after the initial completion in hopes of attempting completion again doesn't help because the underscore demarcates the cite into different words.  Zotero doesn't offer any options to modify its export format.  FWIW I do have the SuperTab plugin installed, and I am on Windows.  I'm new to Pandoc and Zotero (and vim-pandoc of course) so forgive me if I've looked over something obvious.

**Comment by fmoralesc** [comment]
This might be a problem in the legacy bibliography completer. Can you try using the citeproc based one?
~~~ vim
let g:pandoc#completion#bib#mode = 'citeproc'
~~~
(I just tried and it doesn't have this issue.)

This is not related to `iskweyword`.

**Comment by fmoralesc** [comment]
Closing for now.
