### ISSUE TITLE
can't seem to get bib omni-completion working

### ISSUE THREAD

**Issue by parezcoydigo** [vim-pandoc/vim-pandoc#112]
Since switching to the updated plugin from the legacy one, I can't seem to get omnicompletion of bib citations working. Before, I had this in my `.vimrc`:

    let g:pandoc_bibfiles = ['/Users/parezcoydigo/Dropbox/Library.bib']
    let b:pandoc_bibfiles = ['/Users/parezcoydigo/Dropbox/Library.bib']

Reading through the docs, I've tried the whole range of options listed under `g:pandoc#biblio#sources`, including default.bib in my `~/.pandoc` folder, a bib file of the same name as the file in the same folder, setting `b:pandoc_biblio_bibs` and `g:pandoc#biblio#bibs` in my `.vimrc`. But, whatever I do, I get `-- Keyword completion (^N^P) Pattern not found`. Is there a vimrc setting I'm just missing?

**Comment by fmoralesc** [comment]
Can you send a copy of the bibliography?

Have you tried the citeproc-based completer? It is enabled with

     let g:pandoc#completion#bib#mode = "citeproc"

It requires `pandoc-citeproc` to be installed.

**Comment by fmoralesc** [comment]
I just tried vim-pandoc with the default settings, and it works. Did you completely remove the legacy version of vim-pandoc before updating to the new one? If not, it might be interferring. 

Also, it is not necessary to add b:pandoc_biblio_bibs to your vimrc; this is something that should be done manually or using something like https://github.com/embear/vim-localvimrc after a document is loaded, setting it in vimrc won't make any difference (the variable is bound to the buffer).

**Comment by parezcoydigo** [comment]
I have `pandoc-citeproc` installed via homebrew, and have citeproc set in my [.vimrc](<script src="https://gist.github.com/parezcoydigo/510fc0593df7f9f41ce3.js"></script>). Here's the [bib file](<script src="https://gist.github.com/parezcoydigo/bc7c9e0b15d6ef5e2550.js"></script>). 

I'm on a new computer, and the only plugins I have in `.vim/bundle` are supertab, vim-pandoc, vim-pandoc-after, vim-pandoc-syntax, nerdtree, and vim-markdownfootnotes. I'm using vim version 7.4 installed with homebrew.

**Comment by dfaligertwood** [comment]
I don't think it would return that error, but are you running MacVim? And if yes, did you start it via the gui or via the command-line?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: Chad BlackSent: Saturday, 24 January 2015 18:28To: vim-pandoc/vim-pandoc‎Reply To: vim-pandoc/vim-pandocSubject: Re: [vim-pandoc] can't seem to get bib omni-completion working (#112)I have pandoc-citeproc installed via homebrew, and have citeproc set in my .vimrc. Here's the bib file. 

I'm on a new computer, and the only plugins I have in .vim/bundle are supertab, vim-pandoc, vim-pandoc-after, vim-pandoc-syntax, nerdtree, and vim-markdownfootnotes. I'm using vim version 7.4 installed with homebrew.

—Reply to this email directly or view it on GitHub.

**Comment by parezcoydigo** [comment]
dfaligertwood -- I'm not using MacVim. I use vim from the command line, installed via brew. That particular error message comes from using `TAB` completion with SuperTab. But, I get an omnicompletion error if I use `<C>-x <C>-o` instead.

**Comment by fmoralesc** [comment]
I just tried the file, and it works both when I try to access the file from a file in the same folder as the bib (`default.md`), and when using

     let g:pandoc#biblio#bibs = ["/home/felipe/inbox/default.bib"]

(the path must be full). Notice, though, that the citeproc collator is slower than the legacy one for this file (it also provides way more results, which must be improved upon).

**Comment by fmoralesc** [comment]
Also, the completion code requires python support in vim. Perhaps your vim build doesn't have it?

**Comment by parezcoydigo** [comment]
Thanks for you help. Somehow, I've got it working now. I went back through and cleaned up my .vimrc, and reinstalled everything. It's actually working better for my without using `pandoc-citeproc`, which was very slow.

**Comment by fmoralesc** [comment]
Yes, the citeproc path can be slow for large databases since it does a lot of work and it doesn't use any sort of cache (it should). One of the reasons it is not the default :p 

I'm glad the issue could be fixed. As I mentioned above, the legacy and current vim-pandoc's can have collisions (the current vim-pandoc was rewritten from the ground up, it was not a fork), so it is necessary to remove all traces of the old one before updating to it.

**Comment by danilomm** [comment]
I've entered the full path:

	let g:pandoc#biblio#bibs = ["/Users/danilomacedo/Dropbox/_bib/danilo-bib.bib"]

it works in "b" and "c" source options (when the bibfile is in the current folder) but it is not working when I try to add the whole path. 

What may I be doing wrong?
