### ISSUE TITLE
Error when trying to use <localleader>gl

### ISSUE THREAD

**Issue by rafaeln** [vim-pandoc/vim-pandoc#113]
When I position the cursor on the link in the minimal file below:

~~~markdown
# header1

[link](#header2)

# header2

  * something
~~~

and type `<localleader>gl`, instead of seeing the cursor move to `#header2`, I get the error:

~~~
Error detected while processing function pandoc#hypertext#OpenLink..pandoc#hypertext#GotoID:
line    8:
E117: Unknown function: getcurpos
~~~

**Comment by fmoralesc** [comment]
getcurpos() was added in 7.4.313, your vim version might be too old. That
said, I might create a fallback method.

**Comment by rafaeln** [comment]
I see. I wonder if someone knows how to install a newer version of vim under Ubuntu 14.04. I've been googling for the past half an hours and tried a couple of things that didn't work.

**Comment by rafaeln** [comment]
Half an hour more of googling and I figured it out. I'll leave instructions here in case someone else finds themself in my situation:

In order to install `vim 7.4.589-1` on `Ubuntu 14.04`:

 1. `sudo apt-add-repository ppa:pi-rho/dev`

 2. Create `/etc/apt/preferences.d/pi-rho-dev-pin-400` with the following content:

        Package: *
        Pin: release o=LP-PPA-pi-rho-dev
        Pin-Priority: 400

        Package: vim-common vim-gtk vim-gui-common vim-runtime vim-tiny
        Pin: release o=LP-PPA-pi-rho-dev
        Pin-Priority: 500

    (This will ensure the only packages in this ppa that get upgraded are the vim-related ones)

 3. `sudo apt-get update`

 4. `sudo apt-get upgrade`

**Comment by fmoralesc** [comment]
Made vim-pandoc fallback to getpos if getcurpos is not available.

**Comment by rafaeln** [comment]
I've downgraded back to the vim version that comes with Ubuntu 14.04 and it's indeed working perfectly. Thanks!
