### ISSUE TITLE
Error with macvim

### ISSUE THREAD

**Issue by mclearc** [vim-pandoc/vim-pandoc#114]
I can't seem to get vim-pandoc to work consistently with *both* macvim and terminal vim. I have terminal vim installed via homebrew (7.4.1-488) and have tried macvim both via homebrew and via the google-projects site. There seems to be a problem with symlinks. either macvim can call pandoc and terminal can't or vice versa. Any ideas what might be the problem?

**Comment by fmoralesc** [comment]
No clue. I have a barely functioning OSX VM I can test this out, I'll try to see what I can do.

**Comment by fmoralesc** [comment]
Might be something related to the vim binaries default paths not being the same. You can use the homebrew vim for both console and ui with `----override-system-vim`, which is described [here](http://superuser.com/questions/334252/the-best-way-to-make-macvims-vim-console-not-mvim-the-default-instead-of-mac).

**Comment by dfaligertwood** [comment]
Yep, might be a problem with which vim you're using. If it isn't that, could you check if `:! echo $PATH` returns the same for both terminal and gui vims?

**Comment by mclearc** [comment]
So I don't want to use macvim's vim because I want terminal vim compiled with clientserver for asynchronous pandoc builds. Also, homebrew's terminal vim is much further along then macvim. 

PATH is the same for both. 

When I try and install macvim via homebrew after installing vim with hombrew I get the following:

>The `brew link` step did not complete successfully
>The formula built, but is not symlinked into /usr/local
>Could not symlink bin/gview
>Target /usr/local/bin/gview is a symlink belonging to vim. You can unlink it:  brew unlink vim

Obviously I don't want to unlink vim. Just overwriting the problem links as advised like so:

>brew link --overwrite --dry-run macvim
>Would remove:
>/usr/local/bin/gview -> /usr/local/Cellar/vim/7.4.488/bin/gview
>/usr/local/bin/gvim -> /usr/local/Cellar/vim/7.4.488/bin/gvim
>/usr/local/bin/gvimdiff -> /usr/local/Cellar/vim/7.4.488/bin/gvimdiff

Doesn't seem to solve the problem and sometimes breaks my terminal vim use of pandoc. 

I get this error message from macvim when I try and run :Pandoc html -s

>Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Roambot/.vim/plugged/vim-pandoc/pythonx/vim_pandoc/command.py", line 207, in __call__
    output_format = c_args.pop(0) if len(c_args) > 0 and self.opts.in_allowed_formats(c_args[0]) else "html"
  File "/Users/Roambot/.vim/plugged/vim-pandoc/pythonx/vim_pandoc/command.py", line 168, in in_allowed_format
s
    if not identifier.startswith("markdown") and identifier in self.get_output_formats_table():
NameError: global name 'self' is not defined 

I should say that it doesn't always throw an error of this sort. Sometimes after uninstalling and reinstalling macvim just fails silently to compile anything with Pandoc. This may be a homebrew problem more than anything else. But ideas are appreciated!

**Comment by fmoralesc** [comment]
That last error was caused by a bit of sloppiness on my part yesterday, it should work now with vim-pandoc from master.

**Comment by mclearc** [comment]
Good - the error is gone. Now we're just back to failing silently.

**Comment by mclearc** [comment]
Actually it's more specific than I've been reporting. Macvim now seems to be able to call Pandoc and successfully return html, docx, and latex. But it never gives a 'vim-pandoc successful' report, and it doesn't seem to work for md to PDF via latex.

**Comment by mclearc** [comment]
If it helps I've pasted below the content of 'pandoc.out'

>E247: no registered server named "VIM": Send expression failed.
eference bader not found
This is XeTeX, Version 3.14159265-2.6-0.99991 (TeX Live 2014) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(/var/folders/qb/21lwg_mx0hddnjdcjv16_3zr0000gn/T/tex2pdf.27392/input.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2014/texmf-dist/tex/latex/lm/lmodern.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2014/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/fixltx2e.sty)
(/usr/local/texlive/2014/texmf-dist/tex/xelatex/mathspec/mathspec.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/etoolbox/etoolbox.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/etex-pkg/etex.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/local/texlive/2014/texmf-dist/tex/latex/l3kernel/l3unicode-data.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
(/usr/local/texlive/2014/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/fontspec/fontspec-patches.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/euenc/eu1enc.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/euenc/eu1lmr.fd))
(/usr/local/texlive/2014/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/tipa/t3enc.def
(/usr/local/texlive/2014/texmf-dist/tex/latex/euenc/eu1lmss.fd))
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2014/texmf-dist/tex/xelatex/xetex-def/xetex.def))))
(/usr/local/texlive/2014/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/local/texlive/2014/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2014/texmf-dist/tex/generic/xkeyval/xkvutils.tex))))
(/usr/local/texlive/2014/texmf-dist/tex/latex/xltxtra/xltxtra.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/realscripts/realscripts.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/metalogo/metalogo.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/upquote/upquote.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/ts1enc.def)))
(/usr/local/texlive/2014/texmf-dist/tex/latex/microtype/microtype.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/microtype/microtype-xetex.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/microtype/microtype.cfg))
(/usr/local/texlive/2014/texmf-dist/tex/latex/soul/soul.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/setspace/setspace.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/mdwtools/mdwlist.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/lastpage/lastpage.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/lettrine/lettrine.sty
Loading lettrine.cfg
(/usr/local/texlive/2014/texmf-dist/tex/latex/lettrine/lettrine.cfg))
(/usr/local/texlive/2014/texmf-dist/tex/latex/epigraph/epigraph.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/csquotes/csquotes.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/csquotes/csquotes.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/csquotes/csquotes.cfg))
(/usr/local/texlive/2014/texmf-dist/tex/latex/comment/comment.sty
Excluding comment 'comment')
(/usr/local/texlive/2014/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/color.cfg)
(/usr/local/texlive/2014/texmf-dist/tex/latex/colortbl/colortbl.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/tools/array.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/dvipsnam.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/xcolor/svgnam.def))
(/usr/local/texlive/2014/texmf-dist/tex/latex/footmisc/footmisc.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/titling/titling.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/mdwtools/footnote.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/ncctools/manyfoot.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/ncctools/nccfoots.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2014/texmf-dist/tex/latex/url/url.sty))

>Package hyperref Message: Driver: hxetex.

>(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/hxetex.def
(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/stringenc.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))

>Package hyperref Warning: Option `bookmarks' has already been used,
(hyperref)                setting the option has no effect on input line 69.

>(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/se-ascii-print.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/geometry/geometry.sty)
(/var/folders/qb/21lwg_mx0hddnjdcjv16_3zr0000gn/T/tex2pdf.27392/input.aux)
(/usr/local/texlive/2014/texmf-dist/tex/latex/tipa/t3cmr.fd)
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(/var/folders/qb/21lwg_mx0hddnjdcjv16_3zr0000gn/T/tex2pdf.27392/input.out)
(/var/folders/qb/21lwg_mx0hddnjdcjv16_3zr0000gn/T/tex2pdf.27392/input.out)

>Package hyperref Warning: Rerun to get /PageLabels entry.

>*geometry* driver: auto-detecting
*geometry* detected driver: xetex
(/usr/local/texlive/2014/texmf-dist/tex/latex/lm/ot1lmr.fd)
(/usr/local/texlive/2014/texmf-dist/tex/latex/microtype/mt-LatinModernRoman.cfg
) (/usr/local/texlive/2014/texmf-dist/tex/latex/lm/omllmm.fd)
(/usr/local/texlive/2014/texmf-dist/tex/latex/lm/omslmsy.fd)
(/usr/local/texlive/2014/texmf-dist/tex/latex/lm/omxlmex.fd)
(/usr/local/texlive/2014/texmf-dist/tex/latex/microtype/mt-msa.cfg)
(/usr/local/texlive/2014/texmf-dist/tex/latex/microtype/mt-msb.cfg)

>LaTeX Font Warning: Font shape `EU1/Optima(0)/m/sc' undefined
(Font)              using `EU1/Optima(0)/m/n' instead on input line 197.

>[1sh: xdvipdfmx: command not found

>pandoc: Error producing PDF from TeX source

**Comment by fmoralesc** [comment]
There's two issues there. First, it seems like no Vim server was found (which causes the "pandoc succesfull" message not to appear), and second, that the `xdvipdfmx` binary was not found, which pandoc seems to require to create the pdf (not sure, though). Do you have that in your `$PATH`?

**Comment by mclearc** [comment]
I do, and the command works without problem in terminal vim, and both macvim and terminal vim return the same $PATH.

When I call macvim from the command line using 'mvim' it will be able to find and compile the PDF. It still doesn't report the 'vim-pandoc successful' nor does it automatically open a PDF viewer if I've ordered it to using 'Pandoc!'. But the compilation works. It's all very strange.

**Comment by fmoralesc** [comment]
Indeed. I'm trying to test locally, but my VM is a 10.3 (!) POS and it
won't even let me install pandoc (or ghc, for that matter ).

**Comment by mclearc** [comment]
While I'd obviously appreciate any help you can provide, I also don't expect you to spend very much time on what may be a very specific (to me) bug. It may even be that the problems are being generated by Yosemite, in which case your VM will be of no help. But thanks for your efforts in any case!

**Comment by fmoralesc** [comment]
No, my VM is of no help for anybody - it is also impossible to update without breaking (it helped me fix an issue in another vim plugin, though) :/ 

I worry this might be exposing some issue in the way vim-pandoc deals with the async commands, so it is worth taking a look. Have you tried using vim-pandoc with neovim? It uses the job api over that, and it should be pretty modern vim (it has most patches under 7.4.500).

**Comment by mclearc** [comment]
I've worried about the stability of neovim but perhaps I should take a look. It seems to be progressing fairly rapidly. In any case, if I get any new info I'll let you know.

**Comment by fmoralesc** [comment]
Which has `+clientserver`, `mvim` or `vim`? Because checking the code, it tries to launch `vim` to notify the success or failure of the async vim execution. This might be causing that issue for `mvim` if `vim` doesn't have clientserver.

**Comment by fmoralesc** [comment]
Just pushed a small change that could fix this. Please confirm any changes.

**Comment by mclearc** [comment]
Both `vim` and `mvim` have `+clientserver`. I pulled the changes from master and haven't noticed any difference. Calling mvim compiles but doesn't report. Opening macvim from Finder doesn't compile PDF or report anything.

**Comment by mclearc** [comment]
`mvim` is 7.4-73 and `vim` is 7.4.488, if that helps.

**Comment by mclearc** [comment]
Using the current snapshot of Macvim (7.4-74) and overriding the system vim seems to make everything work. At least part of the problem seemed to stem from trying to use Homebrew's vim and Macvim together. Now I just use neovim when using the terminal and everything works (or will once the API issue is resolved). Thanks for looking into this!

**Comment by chusiang** [comment]
Thanks @fmoralesc, I add a alias for this error.

    alias gvir='gvim --remote-tab ----override-system-vim'
