### ISSUE TITLE
vim-pandoc forces hard wrapping on .md, even when g:pandoc#filetypes#pandoc_markdown = 0

### ISSUE THREAD

**Issue by mwpher** [vim-pandoc/vim-pandoc#115]
Hi,

I'm finding that setting `pandoc#filetypes#pandoc_markdown` to 0 does *not* stop hard-wrapping .md files when the automatic hardwrapping is enabled with `g:pandoc#formatting#mode = 'ha'`. This problem does not occur when only hard-wrapping is enabled, as in `g:pandoc#formatting#mode = 'h'`, or when soft-wrapping is enabled.

Thanks! Hopefully this is a real bug and I'm not wasting your time. :)

**Comment by fmoralesc** [comment]
Just pushed a fix for this. Setting `pandoc#filetypes#pandoc_markdown` to 0 will disable all pandoc functionality for markdown files, unless "pandoc" exists in the `pandoc#filetypes#handled` array.

To enable pandoc functionality for markdown files while using  the markdown filetype and syntax, use

     let g:pandoc#filetypes#handled = ["pandoc", "markdown"]
     let g:pandoc#filetypes#pandoc_markdown = 0

**Comment by mwpher** [comment]
It works now! Thank you :)
