### ISSUE TITLE
`:Pandoc pdf` doesn't work

### ISSUE THREAD

**Issue by lyeoh** [vim-pandoc/vim-pandoc#116]
`:Pandoc pdf` tries to run `pandoc -t html -o "FILENAME.html" "pdf" "FILENAME.page"`, giving error message

> pandoc: pdf: openFile: does not exist (No such file or directory)

The problem seems to stem from the function [`get_output_formats_table()`](https://github.com/vim-pandoc/vim-pandoc/blob/master/pythonx/vim_pandoc/command.py#L62) in [`vim-pandoc/pythonx/vim_pandoc/command.py`](https://github.com/vim-pandoc/vim-pandoc/blob/master/pythonx/vim_pandoc/command.py).

It calls `PandocHelpParser._get_output_formats()`, which calls `PandocHelpParser._get_formats()`, which calls `pandoc --help`. `get_output_formats_table()` expects the substring 'pdf' after 'Output formats:' in `pandoc --help`, whereas [it is not there](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc.hs#L249).

For a dirty fix, insert `table["pdf"] = "pdf"` before returning `table` in `get_output_formats_table()`.

**Comment by fmoralesc** [comment]
Ah, once again pandoc updating breaks my feeble hack :p Will try to fix
properly once I get home tonight.

**Comment by fmoralesc** [comment]
I just pushed a fix that should fix this. BTW, are you using `pandoc` from HEAD? I'm still using 1.13.2, which is why I didn't see this behavior.

**Comment by lyeoh** [comment]
I was actually using an old version bundled with `gitit`.

Now that you mention it, I must have misread the source in master. It [explicitly includes](https://github.com/jgm/pandoc/blob/master/pandoc.hs#L913) `pdf*` in its `--help` output, and has since [2013](https://github.com/jgm/pandoc/commit/4edc97a921d011489375eac62519fe3fc24f7609). I'm afraid I was just using a very old version of `pandoc`!

**Comment by fmoralesc** [comment]
LOL. Well, I guess it's safe to close this then ;)
