### ISSUE TITLE
citation filter

### ISSUE THREAD

**Issue by mclearc** [vim-pandoc/vim-pandoc#119]
I'd like to be able to take a markdown file I'm working on and filter all the citation tags in it into genuine citations while keeping the file as a markdown file. This can be accomplished from the command line by typing 'pandoc -t markdown-citations' along with whatever other arguments might be wanted. It seems like vim-pandoc doesn't recognize the command 'Pandoc markdown-citations' when I use it. Could this be added easily? Thanks.

**Comment by fmoralesc** [comment]
Yes, it should be easy. I plan on working on the plugin this weekend, I'll
probably add this too.

On Feb 6, 2015 6:42 PM, "Colin McLear" <notifications@github.com> wrote:
>
> I'd like to be able to take a markdown file I'm working on and filter all
the citation tags in it into genuine citations while keeping the file as a
markdown file. This can be accomplished from the command line by typing
'pandoc -t markdown-citations' along with whatever other arguments might be
wanted. It seems like vim-pandoc doesn't recognize the command 'Pandoc
markdown-citations' when I use it. Could this be added easily? Thanks.

**Comment by mclearc** [comment]
Great. Really appreciate it!

**Comment by fmoralesc** [comment]
I was researching into this, and it seems like using the `markdown` writer and the `--bibliography` arg should be equivalent:

      $ pandoc -t markdown --bibliography bib.bib file.md

     :Pandoc markdown

(assuming vim-pandoc is finding the bibliography files).

See [here](http://johnmacfarlane.net/pandoc/releases.html) under "pandoc 1.11.1". 

Now, the more general issue is vim-pandoc doesn't recognize the extension syntax (`-t markdown-citations` really means "markdown withoout the citation extensions"), so I'll focus on that.

**Comment by fmoralesc** [comment]
Should be fixed now. Notice you'll have to wait a bit for changes to the file too be displayed if you have autoread enabled, or you'll have to read the file again.

**Comment by mclearc** [comment]
It works for me -- thanks again!
