### ISSUE TITLE
Textwidth doesn't work with reflow

### ISSUE THREAD

**Issue by tomak-git** [vim-pandoc/vim-pandoc#122]
I tried to set the textwidth with
```
let g:pandoc#formatting#textwidth = 72
```
in my .vimrc, but when I try to reflow a paragraph (with `gq`), it istill reflows to the default 79 width.
I also tried the normal `set textwidt=72` with no luck.
The only thing that works is to set textwidth through `:set textwidth=72` when editing a document, which gets a little annoying over time ;-)

**Comment by fmoralesc** [comment]
Can't reproduce the issue. Are you using hard or soft wraps? `textwidth` is only effective if hard wraps are used, it reverts to vim's default otherwise (might fix that).

**Comment by tomak-git** [comment]
Tried this after some time and now it behaves a little bit differently: the first file opened with vim gets the width correctly. However, subsequently opened files (for example with :vs) have the default 80 width.

Here are contents of my vimrc file related to the plugin:

`let g:pandoc#modules#enabled = ["formatting", "bibliographies", "completion"]`
`let g:pandoc#formatting#textwidth=72`
`let g:pandoc#biblio#sources = ["g"]`
`let g:pandoc#biblio#bibs = ["/path/to/bibliography.bib"]`
`let g:pandoc#syntax#conceal#use = 0`
`let g:pandoc#after#modules#enabled = ["ultisnips"]`


There are no other settings with regard to width or wrapping.
I'm on ubuntu 15.04 with VIM 7.4.

**Comment by fmoralesc** [comment]
Just tested, and it works fine on my end. Can you check the output of 
~~~ vim 
verbose set textwidth?
~~~
after opening each file? (i.e.; `:e test.md | verbose set textwidth | vs test2.md | verbose ...`). It should say that textwidth is 72 and that it was defined last time by vim-pandoc.

**Comment by tomak-git** [comment]
Ok, this is weird. When I open a file directly (`vim test.md`), the textwidth is set correctly to 72 (confirmed by the output of `:set textwidth?`).

But when I first open vim, and then do `:e test.md`, textwidth is set to zero. The verbose output is:

    "test.md" [new file]
     textwidth=0
     Last set from ~/.vim/bundle/vim-pandoc/autoload/pandoc/formatting.vim

And its the same for opening another file with `:vs`.

In case I missed something, here is my full vimrc file as is: http://paste.ubuntu.com/11330922/

**Comment by fmoralesc** [comment]
I think it isn't using &textwidth because you are not using vim-pandoc's hard wrap mode:

~~~ vim
let g:pandoc#formatting#mode = "h"
~~~
By default it uses soft wrapping, and that resets &textwidth to vim's default.

**Comment by tomak-git** [comment]
Added the line to my vimrc, but the behavior is exactly the same.

**Comment by tomak-git** [comment]
I just found out that due to some messed up symlinks, the changes in my vimrc file were not processed. I fixed it an your last suggestion works like a charm!
Thank you and sorry for the confusion.

**Comment by fmoralesc** [comment]
No problem,  and at least you could fix the issue. :+1:
