### ISSUE TITLE
Consider :PandocFolding none

### ISSUE THREAD

**Issue by pasha2718** [vim-pandoc/vim-pandoc#123]
It would be useful to turn pandoc folding off for a buffer, without disabling the module entirely.  One way to do this would be to add a fourth option to :PandocFolding as "none" or "off".

This would mainly mean modifying "none" to `pandoc#folding#ModeCmdComplete(...)` and adding an if/else to `pandoc#folding#ModeCmd(mode)` in folding.vim.  Is this an appropriate usage of the concept?

**Comment by fmoralesc** [comment]
Just pushed an implementation of this. Sorry for the delay!
