### ISSUE TITLE
pandoc or pdflatex, too many variables?

### ISSUE THREAD

**Issue by m-ichael** [vim-pandoc/vim-pandoc#124]
every variable has been eliminated by conscientious testing:

pandoc to pdf from the command line
vim-pandoc to pdf
both generate all files problemless in all subdirectories of parent ~ , the home directory. Meaning ~/anyfolder/anymarkdownfile.mk will problemless generate pdf output.
all permissions and all ownership group variables are identical for all files and directories.
both processes, pandoc from the command line, or from within vim do NOT generate any markdown to pdf in ~ , the home directory, the one-level up, parent from ~/anyfolder and in any folder below ~/anyfolder/ meaning any subdirectory of ~/anyfolder/anysubdirectory/anymarkdownfile.mk
using the same binaries: for pandoc, pdflatex in both processes.  
using the same flags in both processes
Concerning latex further: anyplace within the fil system pdflatex from the command line, or using atp-plugin within vim will process all the above .tex files in all the above directories
The .tex files were generated by pandoc and vim-pandoc, both were tested and were no further modified.  Then running pdflatex command line, makelatex command line, atp-plugin :makefile problemless produce all files in all directories
Conclusions preliminary: 
- it cannot be latex, the same pdflatex binary is used in all processes, and processes problemless pdf files.
- it cannot be the directory structure, the test environment was identical
- then pandoc on the command line  and within vim choke in the same way, this is the error:
( start error message in quickview vim, the command line message is identical )
~~~
# Press q to close this
▶ pandoc --bibliography "/Users/m___/bibdirectory/main.bib" --latex-engine=/usr/texbin/pdflatex -o "testcom.pdf" --trace --template="/Users/m___/.pandoc/note/note.latex" --csl="/Users/m___/.pandoc/note/side_no_bib.csl" --filter=pandoc-citeproc --chapters "testcom.pdc"
line 6: [Header 1 ("superficielle-premiere-cape-de-la-realite",["unn
line 9: [Header 2 ("and-a-section-title-to-be-removed",[],[]) [Str "
line 12: [Para [Str "Remettons",Space,Str "dans",Space,Str "les",Spac
line 15: [Para [Str "C\8217etait",Space,Str "ma",Space,Str "pronostiq
line 17: [CodeBlock ("",[],[]) "Au pouvoir ils arriveront, en Europe 
line 39: [Para [Str "Notre",Space,Str "soucis",Space,Str "a",Space,St
line 41: [Para [Str "L\8217ecole",Space,Str "n\8217aidera",Space,Str 
line 43: [Para [Str "Plus",Space,Str "que",Space,Str "dans",Space,Str
line 45: [Para [Str "ps:",Space,Str "l\8217internet",Space,Str "remar
line 49: [Para [Str "On",Space,Str "230302015,19:54",Space,Str "de",S
line 57: [Para [Str "\8220Entre",Space,Str "paranteses:",Space,Str "l
line 54: [BlockQuote [Para [Str "\8220Entre",Space,Str "paranteses:",
line 51: [BlockQuote [BlockQuote [Para [Str "\8220Entre",Space,Str "p
line 58: [Para [Str "On",Space,Str "entre",Space,Str "une",Space,Str 
line 56: [BlockQuote [Para [Str "On",Space,Str "entre",Space,Str "une
line 54: [BlockQuote [BlockQuote [Para [Str "On",Space,Str "entre",Sp
line 62: [Para [Str "L\8217instinct",Space,Str "de",Space,Str "survie
line 60: [BlockQuote [Para [Str "L\8217instinct",Space,Str "de",Space
line 56: [BlockQuote [BlockQuote [Para [Str "L\8217instinct",Space,St
! Missing number, treated as zero.
<to be read again> 
                   \par 
l.1 

pandoc: Error producing PDF from TeX source
------------------------------------------ end output ----------------------------          
~~~
pandoc does markdown to tex on all locations, to html on all locations 
pandoc to pdf referring to the standard template.latex file as in pandoc -o file.pdf  file.mk WORKS on all locations in the file system.
So: it can only be the custom.latex template i use, but then how would this same template function in one location and not in the other
Is the culprit the path indicator in the custom command?  It is not deductible from the error output as pasted above, neither from the vim-pandoc-templates file of which the content is printed below.
---------- vim-pandoc-templates file with custom commands ------------------------------
~~~
~: cat .vim/vim
vim-pandoc-templates      vim-pandoc-templates.ori  vimrc
 ~: cat .vim/vim-pandoc-templates
notebook_plain|plain --trace --standalone --toc --chapters --bibliography=/Users/m___/bibdirectory/main.bib  --csl=/Users/m___/.pandoc/notebook/side_no_bib.csl --filter pandoc-citeproc 
notebook_html|html --trace --self-contained --standalone  --css=~/.pandoc/notebook/notebook.css --bibliography=~/bibdirectory/main.bib --csl=~/.pandoc/notebook/side_no_bib.csl --filter pandoc-citeproc --chapters --toc --toc-depth=2 
notebook_pdf|pdf -s --trace  --standalone --template=/Users/m___/.pandoc/notebook/notebook.latex --bibliography=/Users/m___/bibdirectory/main.bib --csl=/Users/m___/.pandoc/notebook/side_no_bib.csl --filter pandoc-citeproc --chapters --toc --toc-depth=2 
note_pdf|pdf  --trace --template=/Users/m___/.pandoc/note/note.latex  --csl=/Users/m___/.pandoc/note/side_no_bib.csl --filter pandoc-citeproc --chapters 
note_html|html --trace --self-contained --css=~/.pandoc/note/sol.css --bibliography=/Users/m___/bibdirectory/main.bib --csl=~/.pandoc/note/side_no_bib.csl --filter pandoc-citeproc --chapters --toc --toc-depth=2
note_plain|plain --trace --standalone --toc --chapters --bibliography=/Users/m___/bibdirectory/main.bib  --csl=/Users/m___/.pandoc/note/side_no_bib.csl --filter pandoc-citeproc 
~~~
----- end of output vim-pandoc-templates -----------------------------------------------------
the lines concerning the command used are:
~~~
note_pdf|pdf  --trace --template=/Users/m___/.pandoc/note/note.latex  --csl=/Users/m___/.pandoc/note/side_no_bib.csl --filter pandoc-citeproc --chapters 
~~~
... as can be seen the paths used are absolute, and again, the same command does fine in the first level on all locations below ~ , the home directory.  

Eliminated all variables to think of, what has been looked over. 
ps: the template file above carries the same code as the code used by atp-plugin and latex from the command line, and again apart from the place in the file structure the same variables work ...or not.

some-one please?

**Comment by fmoralesc** [comment]
Sorry for the delay. Is this still an issue? From the data you gave, I couldn't detect the source of the problems, although it seems like pandoc spat some data in the native format for some reason. For example:
~~~
line 6: [Header 1 ("superficielle-premiere-cape-de-la-realite",["unn
line 9: [Header 2 ("and-a-section-title-to-be-removed",[],[]) [Str "
line 12: [Para [Str "Remettons",Space,Str "dans",Space,Str "les",Spac
~~~
are all not really LaTeX.

**Comment by m-ichael** [comment]
The devil's advocate,

The issue was solved but thanks for the reply.
Using a Tufte stylesheet, and Tufte-latex
code in the template, ...and Tufte not allowing for more then two levels
in headers ...pandoc choked, discovered by accident.

Systemically: neither Tufte-handout nor Tufte-book, nor Pandoc is
deep-documented. 
That leaves many inexplicable anomalies.
As long as Pandoc is manipulated outside the default latex template,
something is due to err.
The error messages are as the latex ones arcane.
Html is a much less demanding format, if one adds css.
The latex template manipulation is ill documented.
The semantics and syntax of pandoc are not really well addressed in the
user manual.
It is a long shot to learn Haskell, and Python, and Latex, and
bash-scripting, and css and pandoc's syntax and semantics, 
and decide on one's own for most of our academics brightest.
Academics are a cranky lot, since their focus is on man-man documenting.
Not being able many still to have a man-machine communication ability.
This is a serious deficiency, it is to question how they are searching,
finding files, diff-ing between two files, replacing text.
One only needs to see the propositions of the digital publishing
companies offers, and their tools to search within their database, the
universities and colleges just putting a front, one more layer to their
offers and have this act as a library.
Pandoc in all comes closest to a practical solution of one source and in
my case, html and pdf outputs.
Add epub for good measure.
That said pandoc goes when one has notions of bash scripting, latex,
css, the command line in general, bibtex, vim or similar customizable, keyboard 
friendly editor, grep-find-diff commands or their equivalents-overlayered 
brethrens ag, ack, git-grep..., git or similar versioning, an online server space to push
the repos as a back-up to the local ones, to have a working relation between
man-machine.
To have a minimum of independence of proprietary tools, and highly
inefficient documenting due to spending more time in churning out the
documentation skeleton then focussing on content, all of the above
skills are minimal.
Most professors, academics, scholars and certainly students are cases of
man-machine ignorance at this level.

Suggestion: for pandoc: pandoc-latex translation 
should be in-depth documented.
Suggestion: latex has two larger negatives, one, the mega-data, commands in the
text are obtrusive when focussing on editing. 
These commands can be called using snippets in all of their complexity,
the issue rather is the obtrusive blob that impedes to prioritize the
oversight of the content.
This could maybe be solved with something like "conceal". 
Latex does turns the most sophisticated typesetting results ...in
pdf. 
But... latex to anyting else is a second job all over, especially to
html.
The only semi-solution is to have browser open up pdf links within html
pages. 
Pdf looks rather well in a browser, and can serve as a digital
alternative to html.
Convention does not address this well, never saw an argumentation why
pdf is inferior as a self contained page in the browser to a "broadcast"
html page, behind a regular index page allowing for if needed,
interactivity between the end-user and the server.
A browser could be tweaked to beautifully display pdf on any mid-size
monitor.
In depth: why not turn the display so as to be favourable to the reading
and manipulation of text, which is the primary use of most computers in
research and school environments.
The analog book stands taller then it has girth, why a monitor is squat
as a tv, but should be suitable to short lines of text and smooth
scrolls.
Since a pdf is always self-contained, the portability is A-one.
For the rare occasions in print, pdf and not html are less cumbersome.
So in the latex case to stand superior to pandoc it should have syntax
code a la pandoc-syntax that masks the verbosity of the commands while
editing, authoring source text.
Command code reappearing when the cursor hoovers over the specifics.

In short: pandoc is a crude tool concerning pdf as compared to latex,
but this could be addressed, to have it fit as a smooth latex plugin to
output pdf(the positioning of the images, style issues in template.latex
and referenced style sheets, documentation), it is problemless in
turning out html self-contained pages. 
Html is definitely the easier format.

Pandoc could be a tool to stand time, in a unix environment that is not
proprietarized.

All of the above: progress in systemic address to documenting is needed,
as a measure, most of what programmers work on is hype, commercial
motivations priming to real solutions, and educating the end-user into
convenience ...as far as the corner.
Very little is done to enable and educate the user in tools that are
logical, consequential and durable, ...a picture of our society.

**Comment by fmoralesc** [comment]
Thanks *a lot* for the reply.

It is entirely true than the tools academics (vim-pandoc included, for which I take responsibility) have to work with under *nix are way too poorly documented, and one has to take care of way too many things at once. Not everyone has the time to examine every nook and cranny, and to understand how all the pieces work together, and in turn it is difficult to handle issues like the one you described in this issue, which unfortunately we couldn't even resolve properly... 

The few people working on the issues (like myself) are also having little success in transferring the knowledge of the systems they create to their users, which creates a situation where users depend on them to figure out what to do when tools break, and in many cases time is limited and there are external constraints. Sometimes I wish I could dedicate oneself entirely to solving these issues, because at the bottom of it, tool-crafting serves a very important role in enabling people to get things done. It is meaningful work.

 If only our means were not so limited still... *per aspera ad astra* and so on..

**Comment by m-ichael** [comment]
The global systemics are flawed, a "job" means, adding to pertinent
riches of men(mostly and generationally) in power.
Often dumb-struck beyond there own life-bulb, not even considering their
direct descendants as in the case of climate change and anthropogenic
blistering.
Power is the opposite of potential, doing something useful, in depth,
requires primary oversight, in our society there is no ego nor economic
reward for that.
Social intelligence collides with rational through-sight, scientific(the
real science efforts which are sparse), long-term planetary ethics. 
In biology that translates into fever.

Appreciate your efforts,
Use your pandoc to author anything since last January 02015, and it
is functional. 

A little tweak most useful, in my set-up, vim-pandoc: ':Pandoc: #html'
and ':Pandoc: #pdf' give exactly the same output as command-line
commands: 'pandoc -o file.html file' and 'pandoc -o file.pdf file' .
Note the command line pandoc customization through an alias is identical
for pdf and html.
One just needs to ask for -o 'either html or pdf'
The alias in my ~/.bash_rc is:
'alias pandoc='pandoc -S --trace --standalone
--template=/Users/m___/.pandoc/note/note
--css=/Users/m___/.pandoc/note/sol.css --toc --toc-depth=2
--highlight-style=kate --filter pandoc-citeproc
--bibliography=/Users/m___/bibdirectory/main.bib
--csl=/Users/m___/.pandoc/note/side_no_bib.csl'
...and it does the trick, for both pdf and html.
No surprises using pandoc on the command line or within vim, the output
looks identical, and reduces the variables.

The '-H header_file_include' option for html is also useful per case, it allows for static
webpages including the google(horror) code snippet for third party
analytics.

m.
