### ISSUE TITLE
YAML not folding

### ISSUE THREAD

**Issue by ivotron** [vim-pandoc/vim-pandoc#125]
Upgraded to latest version today and noticed this. I have `let g:pandoc#folding#fold_yaml=1` on my vimrc. However, the YAML front matter doesn't fold as expected. Any ideas on how to determine why? Anything else folds OK.

**Comment by fmoralesc** [comment]
can you send me a sample document where this happens? that would help a lot

**Comment by ivotron** [comment]
A simple example suffices:

```
---
layout: post
title: Blogging Like a Hacker
---

# yeah

oh yeah, now I blog like a hacker
```

I think the issue is when the plugin loads. If I try to fold the header I get the message `E490: No fold found`. The conf I use:

```
let g:pandoc#modules#enabled=["folding", "formatting"]
let g:pandoc#formatting#mode="h"
let g:pandoc#folding#fold_yaml=1
let g:pandoc#syntax#codeblocks#embeds#langs=["YAML", "ruby", "cpp", "c", "bash=sh", "python"]
```

`vim-pandoc` is the only active plugin

**Comment by fmoralesc** [comment]
Thanks. Does the folding work if you use vim-pandoc alongside
vim-pandoc-syntax? The folding of YAML headers might use the syntax
assisted folding path, which requires v-p-s... This is probably an
oversight on my part, though, will make it so this part of the code works
independently if there is YAML support.

**Comment by fmoralesc** [comment]
Pushed some fixes. The YAML headers still needs begin at line 1, though. The issue was the yaml syntax was updated and the syntax names vim-pandoc checked were outdated.

**Comment by ivotron** [comment]
Tested today and works ok now. Thanks a lot!
