### ISSUE TITLE
neovim and python

### ISSUE THREAD

**Issue by mclearc** [vim-pandoc/vim-pandoc#126]
Not sure if this is a neovim problem or a problem with vim-pandoc, but just recently, when I try to build a file with vim-pandoc in neovim I get the following:

>Error detected while processing function pandoc#command#Pandoc..provider#python#Call:
line    1:
NvimError("Vim(autocmd):E216: No such group or event: JobActivity pandoc python pandoc.on_done(True, '0')",)
Error detected while processing function pandoc#command#Pandoc:
line    5:
E171: Missing :endif

The command works fine in vim 7.4.622. I have neovim version 0.0.0-alpha+201504062237

**Comment by fmoralesc** [comment]
it seems like the job API changed in neovim, I'll update it ASAP

**Comment by mclearc** [comment]
Just wondering if there's been any progress on this? I'm happy to try and provide more info if necessary (sorry I can't contribute anything on the code side)

**Comment by fmoralesc** [comment]
I'm just getting back to these things (been really busy irl with job and my phd postulation...), but I might take a shot at fixing this later today.

**Comment by fmoralesc** [comment]
Just pushed a fix for this. Please confirm.

**Comment by mclearc** [comment]
Looks fixed. Thanks again!
