### ISSUE TITLE
Functions using ToggleOperator don't work without xterm_clipboard support

### ISSUE THREAD

**Issue by mruwek** [vim-pandoc/vim-pandoc#127]
Trying to use ToggleEmphasis with `\iw` gives me this:

```
Error detected while processing function pandoc#keyboard#styles#ToggleEmphasis..pandoc#keyboard#styles#ToggleOper
ator:
line   34:
E354: Invalid register name: '*'
Press ENTER or type command to continue
Error detected while processing function pandoc#keyboard#styles#ToggleEmphasis..pandoc#keyboard#styles#ToggleOper
ator:
line   40:
E354: Invalid register name: '*'
```

vim 7.4 on any terminal emulator on Gnome 3.14.2 on Fedora 21

I've done some research and it works on gvim, probably because it was compiled with +xterm_clipboard. Quick and dirty hack for using vim in terminal emulator would be then `alias vim='gvim -v'` in `.bashrc`, but it won't work in console, as console can't use X11 clipboard (obviously).

Reverting 7159242b313f817fece845ff1864ef0f1bfdb09d solves the issue, but I presume this kind of solution doesn't satisfy You. Maybe take a look at [tpope/vim-surround](http://github.com/tpope/vim-surround) code? `ys` does pretty much same thing as ToggleOperator and it works *everywhere*.

By the way - thanks for such a great plugin!

**Comment by fmoralesc** [comment]
Will see what I can do

**Comment by fmoralesc** [comment]
Sorry for the delay. Pushed a fix. Please confirm.

**Comment by mruwek** [comment]
Sorry, but it's not working. Still the same error message.

**Comment by fmoralesc** [comment]
The previous fix was incomplete. It should be fixed for real now.

**Comment by mruwek** [comment]
> It should be fixed for real now.

And as far as I can see it **IS** :)

**Comment by SlackerJack** [comment]
I was having this problem with the terminal as well (os x iterm) It worked with gvim just fine. My Vim reports that it has clipboard support, but it does not have the * register. I changed has('clipboard') to has('gui_running') in autoload/pandoc/keyboard/styles.vim and now it works in vim and gvim. Not sure that's the best solution though...

**Comment by fmoralesc** [comment]
@SlackerJack I think you need to use the same version for gvim and terminal vim, it seems like you currently don't. I'll think about this...
