### ISSUE TITLE
vim-pandoc fails to execute if not run in shell

### ISSUE THREAD

**Issue by valeth** [vim-pandoc/vim-pandoc#128]
If vim is run outside of a shell, for example <code>konsole -e vim ...</code>
vim-pandoc creates a [pandoc.out](https://gist.github.com/valeth/02eeffbd5d19d35dda1b#file-vim-pandoc-python-trace-txt) file containing a python traceback

**Comment by fmoralesc** [comment]
What contains the traceback?

**Comment by valeth** [comment]
@fmoralesc heres the traceback

Traceback (most recent call last):
  File "/home/valeth/.xdg/share/vim/plugins/vim-pandoc/pythonx/vim_pandoc/async.py", line 39, in <module>
    Popen(command)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1379, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.4/os.py", line 770, in fsencode
    raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
TypeError: expect bytes or str, not NoneType

**Comment by fmoralesc** [comment]
Doh! Sorry for asking for that, somehow I passed over the link. If you add
~~~ python
    print(command)
~~~
before the `Popen(command)` line at the end of the file, what is the output? (it should be in the new `pandoc.out` file). It seems like somehow we are passing `None` instead of the correct command... I thought it was an issue with the `pandoc` executable not being detected, but the script should fail on that case...

**Comment by fmoralesc** [comment]
I meant the `vim-pandoc/pythonx/vim_pandoc/async.py` file, btw.

**Comment by valeth** [comment]
[None, '--servername', 'GVIM', '--remote-expr', 'pandoc#command#PandocAsyncCallback(0,0)']

the rest is the same

**Comment by fmoralesc** [comment]
That looks like the `async.py` script can't find `{g,m}vim` in the $PATH for some reason.

**Comment by valeth** [comment]
If I execute <code>:echo $PATH</code> in vim the path seems to be set correctly.

**Comment by valeth** [comment]
<code>find_executable('gvim')</code> returns <code>None</code>
<code>None != '' == True</code>

**Comment by fmoralesc** [comment]
What about outside vim? I think I figured out a possible fix, though, I just pushed it.

**Comment by valeth** [comment]
couldn't we just test simply with <code>if find_executable("vim")</code>
if it is None it should be False anyway

**Comment by fmoralesc** [comment]
Ah, didn't see that last comment. Yes, the fix I just pushed should fix this issue.

**Comment by valeth** [comment]
It works fine now, thanks
