### ISSUE TITLE
Prevent soft line wrap between @ and citation

### ISSUE THREAD

**Issue by sjackman** [vim-pandoc/vim-pandoc#129]
So that
```Text [@citation]```
does not wrap as
```
Text [@
citation]
```
Wrapping as
```
Text
[@citation]
```
would be better.

**Comment by fmoralesc** [comment]
Sure, that's a good idea.

**Comment by fmoralesc** [comment]
Meanwhile, try out using `set breakat-=@`. Keep in mind this is a global setting, though.

**Comment by sjackman** [comment]
Thanks, that worked nicely.

**Comment by fmoralesc** [comment]
I'll make it so vim-pandoc adjusts the value of 'breakat' when entering and leaving the documents buffers. I'll try to implement it when I get home later today.

**Comment by fmoralesc** [comment]
Just pushed a fix. vim-pandoc should handle this automatically now ;)

**Comment by sjackman** [comment]
Thanks, Felipe!
