### ISSUE TITLE
how to prevent `set spell` on opening a mardown file ?

### ISSUE THREAD

**Issue by cedricvanrompay** [vim-pandoc/vim-pandoc#135]
When I open a markdown file vim-markdown triggers `set spell`.

I don't want that. I want "no spell checking" as default. where should I do that ? I guess it does not work if I just write `set nospell` in my `.vimrc` since `.vimrc` is only read at vim start.

Thanks for the help.

**Comment by fmoralesc** [comment]
Add
~~~
let g:pandoc#spell#enabled = 0
~~~
to your vimrc.

**Comment by cedricvanrompay** [comment]
fantastic ! thanks

**Comment by cckuu** [comment]
Thank fmoralesc !! I been loooking for this solution high and low ... 
It work for me ... using plastic boy markdown.
