### ISSUE TITLE
Neovim not opening applications with "Pandoc!" command

### ISSUE THREAD

**Issue by mclearc** [vim-pandoc/vim-pandoc#139]
While neovim successfully executes vim-pandoc commands, it won't open the related applications. So, for example, when I run:

`Pandoc! pdf -s  -N -V mainfont=Optima --latex-engine=xelatex --smart --bibliography=/Users/Roambot/Dropbox/Work/Master.bib`

it produces a PDF and I get the "vim pandoc: run successfully" message. But the default PDF reader doesn't open the file. All this works fine with vim. 

Environment is:

`````
CPU: quad-core 64-bit broadwell
OS X: 10.10.4-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
Java: 1.6.0_65
Nvim: 0.0.0-alpha+201507232235 (compiled Jul 24 2015 22:31:26)
````

**Comment by fmoralesc** [comment]
I can't test in OSX, so this might be difficult to fix on my end. Is this valid to open a document with the associated program on that platform?

     $ open document.pdf

Does python sypport `os.devnull` there? The launching of the program is guarded on that:

~~~ python
if sys.platform == "darwin" or sys.platform.startswith("linux"):
     if sys.platform == "darwin":
          open_command = "open" #OSX
     elif sys.platform.startswith("linux"):
          open_command = "xdg-open" # freedesktop/linux

     with open(os.devnull, 'wb') as fnull:
          Popen([open_command,  self._output_file_path], stderr=fnull)
~~~

**Comment by mclearc** [comment]
I'm not totally sure I know the answers. But certainly the "open" command works on OSX. And `Pandoc!` works fine in terminal and macvim (version 7.4). So something is specifically wrong with the way Neovim is calling vim-pandoc to open the file.

**Comment by fmoralesc** [comment]
Sorry for taking so long, but this should be fixed in the last version in HEAD. I found out neovim's python host doesn't change directory with vim, so the executor couldn't find the produced document.
