### ISSUE TITLE
I can't get the formatting to work proper

### ISSUE THREAD

**Issue by marcblabla** [vim-pandoc/vim-pandoc#144]
Hi 

I have the following in my .gvimrc
```
let g:pandoc#formatting#mode = "sA"
let g:pandoc#formatting#smart_autoformat_on_cursormoved = 1
let g:pandoc#formatting#textwidth = 80
```
But unless I set formatoptions+=t. It does not wrap lines, it just makes long lines. 
I'm I missing something to get the smart autoformat to work?

I'm using Macvim 7.4 (77) and the vim is 7.4.769.

**Comment by fmoralesc** [comment]
If you want to break lines at a certain width, you'll need to use
~~~ vim
let g:pandoc#formatting#mode = "hA"
~~~
instead. `...#textwidth` is not used when in soft mode (`...#mode` =~ 's').

**Comment by marcblabla** [comment]
If I set the formatting to hA it still does not wrap the lines. 

I might be my missing/poor undestanding of hard and soft wrap's. But I'm comming for vim-pencil and shoulded the soft wrap in pandoc work the same way as vim-pencil soft.

**Comment by fmoralesc** [comment]
Please describe it, I never use soft wrapping, and I have little experience
with vim-pencil

**Comment by marcblabla** [comment]
First thanks for the quick reply's.
I set it up to use 'ha' now. And that seems to work fin now. And i'm not quit sure what vim-pencil does in soft wrap. Because it seems to me that there is not that much difference between the soft and hard. But again it migth be my limited understanding of the whole wrap thing. 

But one last thing, what is the difference between smart and none smart autoformat?

**Comment by fmoralesc** [comment]
The difference between soft and hard modes in vim-pandoc is that in the first no line breaks are inserted after `textwidth` (the  line breaks are thus "soft"), while that happens in the second.

The difference between 'a' and 'A' is that the first is that the second tries to guess what formatting rules should be applied to the text looking at the context of the cursor (taking hints from the syntax highlighting), while in the first case vim autoformatting is merely enabled with some default settings. I suggest 'A' unless performance is affected (it can be a bit slower when trying to figure out things). For example, rules for indentation in list items are different than in regular paragraphs when using 'A', while 'a' makes no difference about this.

**Comment by marcblabla** [comment]
Ok, thanks.
