### ISSUE TITLE
disable auto set of `conceallevel=2`

### ISSUE THREAD

**Issue by cedricvanrompay** [vim-pandoc/vim-pandoc#148]
I don't like concealing so I put this in my `.vimrc`:
    set conceallevel=0

However it seems that whenever I open a markdown file `conceallevel` is re-set to 2. It does not happen if it is not a markdown file.

I can't find a way to disable that re-setting to 2.

**Comment by fmoralesc** [comment]
Use
~~~ vim
let g:pandoc#syntax#conceal#use = 0
~~~
to disable conceals for markdown files. This is handled by vim-pandoc-syntax, see `:help vim-pandoc-syntax-configuration`.

**Comment by cedricvanrompay** [comment]
Thanks, did not notice it was vim-pandoc-syntax doing it.

**Comment by alerque** [comment]
@alexzanderr This plugin has no bearing on JSON files. Please find the appropriate issue tracker for `vim-jsonc`.
