### ISSUE TITLE
Display \langle and \rangle with their respective unicode characters

### ISSUE THREAD

**Issue by arteymix** [vim-pandoc/vim-pandoc#149]
I couldn't figure where the substitution is performed in the code. Here they are: 〈 〉 (respectively `\langle` and `\rangle`.

**Comment by fmoralesc** [comment]
Sadly, this is handled by vim's LaTeX support instead of by vim-pandoc-syntax, so I can't fix this directly. You can contact the maintainter, Charles Campbell, at drchip@campbellfamily.biz (He is a very helpful person, but might take a while to reply if he's busy).
