### ISSUE TITLE
Section key mappings not working correctly

### ISSUE THREAD

**Issue by rafaqz** [vim-pandoc/vim-pandoc#150]
Sections key commands are kind of working but all the commands seem to get stuck on random dot points instead of just headers. aS iS ]] [[ \<localleader\>hn \<localleader\>hp etc. etc. all do this, and it really seems quite random which dot point is seen as a header.

I'm using the latest vim and latest vim_pandoc.

**Comment by fmoralesc** [comment]
What do you mean by "dot point"? What sort of header are you using? Is this for textile documents?

**Comment by rafaqz** [comment]
I'm using markdown. But sorry that was a bit vague. I'll try to be clearer:

Say I have this markdown file with some text:

    ## first heading
    - foo
    - bar

    sometext

    ### next heading

The cursor is on the first heading somewhere and I use \<localleader\>hn to 'move to the next heading' as it suggests in :help pandoc. But it jumps to - bar instead. Or - foo instead. It doesn't seem to stop on sometext in many cases.

If I'm in visual mode with bar selected, and I hit aS to 'select a section, including header', maybe only foo will be added, not the actual heading. 

It works the same way every time for the same file, with the same weird logic.
