### ISSUE TITLE
E492: Not an editor command: Pandoc

### ISSUE THREAD

**Issue by eriklinde** [vim-pandoc/vim-pandoc#152]
I have tried installing `vim-pandoc` in every possible way (including in Vim, Neovim, and using Vundle and Pathogen), but still, it does not recognize the 

    :Pandoc

command.

When I type `:Pandoc`, I get the following error message:

    E492: Not an editor command: Pandoc

My `.vimrc` file looks as follows:

````
set nocompatible      
filetype off         

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax' 
Plugin 'mattn/vim-calendar' 
call vundle#end()   

filetype plugin indent on  
````

(I intentionally deleted my `~/.vim/bundle` directory and old `.vimrc` file and started over with a brand new `.vimrc` file in order to be able to isolate this error.)

Other `Vundle` installed packages work fine. For example, I included `mattn/vim-calendar` as an example, and typing `:Calendar` works just as expected. 

Further, `pandoc` is installed and working fine on my system; for example, 

    which pandoc

gives me

    /usr/local/bin/pandoc

Any idea what I am missing here?

I am using VIM 7.4.488, with Python support.

    :echo v:version >= 704 && has("python")

returns 

    1

Any idea what I am doing wrong here?

Thanks so much for the help in advance!

**Comment by fmoralesc** [comment]
The `:Pandoc` command is defined only for the associated filetypes. Is the filetype of the files either `pandoc` or `markdown`? You can try to execute
~~~ vim
    :setfiletype pandoc
~~~

before calling `:Pandoc`.

**Comment by eriklinde** [comment]
That settles it! I was using RMarkdown (`.rmd`). Thanks a bunch for the quick response!! :)
