### ISSUE TITLE
Default g:pandoc#formatting#equalprg

### ISSUE THREAD

**Issue by gzagatti** [vim-pandoc/vim-pandoc#155]
Hello,

I believe that the default variable value `g:pandoc#formatting#equalprg = "pandoc -t markdown --reference-links [--columns {g:pandoc#formatting#textwidth}|no-wrap]"` is deprecated. According to [Pandoc documentation](http://pandoc.org/README.html#general-writer-options), the option `--no-wrap` has been deprecated. It is now a synonym for `--wrap=none`.

Second, the default value does not seem to perform the required expansion of `{g:pandoc#formatting#textwidth}` within the quotes.

My solution was to set the `g:pandoc#formatting#equalprg` to `pandoc -t markdown --reference-links --columns='.g:pandoc#formatting#textwidth` such that the required expansion can be performed.

**Comment by fmoralesc** [comment]
The `--no-wrap` issue was recently fixed in https://github.com/vim-pandoc/vim-pandoc/commit/76517f264f5a14848e39517ad115d848b96eb8ad

I'll look into the second issue.

**Comment by gzagatti** [comment]
Ok thanks

**Comment by javiertury** [comment]
Maybe it would be better to keep it for a few months until distributions catch up with the latest pandoc release. On Fedora 23 with pandoc 1.13 after pressing _=_  in vim, instead of aligning the text, it is substituted with:

`pandoc: unrecognized option '--wrap=none'`
