### ISSUE TITLE
Add pandocHRule to the default smart_autoformat_blacklist

### ISSUE THREAD

**Issue by dnguyen85** [vim-pandoc/vim-pandoc#156]
Please consider adding `pandocHRule` to the default `g:smart_autoformat_blacklist`, as previously done with `'pandoctable'` in commit bbbc13b874707b19410de82c22d882649a3f464b. This is to prevent autoformat of paragraph from being activated before users have a chance to type a character on the next line and mark it as a `pandocYAMLHeader`, which will then disable autoformat. 

As an example:
```
--- 
|<This region will be marked as pandocHRule and fo+=a>
```
If you type something, say `a`, the output will be autoformatted to
```
--- a
```
and therefore will not be considered as a `pandocYAMLHeader` region.

**Comment by fmoralesc** [comment]
Just added a fix for this issue.
