### ISSUE TITLE
TypeError when output to pdf

### ISSUE THREAD

**Issue by skinamarink** [vim-pandoc/vim-pandoc#167]
Hi,

When trying to output to pdf using :Pandoc pdf or :Pandoc! pdf, I get the following error:

```
Error detected while processing function `pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/osman/.vim/plugged/vim-pandoc/pythonx/vim_pandoc/command.py", line 221, in __call__
    engine_arg = "--latex-engine=" + vim.vars["pandoc#command#latex_engine"] if output_format in ["pdf", "beamer"] else ""
TypeError: Can't convert 'bytes' object to str implicitly
```

Saving to docx and html both work.

Thank you!

**Comment by kraxli** [comment]
this seems to be a python3 problem. Do you have python 2 support in vim? I solved this problem by installing vim with python 2 (:version should output +python) support instead of python3.

**Comment by kdmurray91** [comment]
@kraxli that isn't a sufficient fix for me, I use other plugins that require python3. There are python2 and 3 compatible ways of writing the code in question, and if no-one beats me to it, I'll fix this next week

**Comment by kiryph** [comment]
@kdmurray91 Did you fix this?
I use precompiled MacVim from https://github.com/macvim-dev/macvim/releases which by default only supports either +python2 or +python. This is documented here: https://github.com/macvim-dev/macvim/wiki/Python-2.x-and-Python-3.x.
I wanted to switch from ctrlp to denite which requires python3.
