### ISSUE TITLE
Go To internal hyperlink crashes for certain headers

### ISSUE THREAD

**Issue by PurpleGuitar** [vim-pandoc/vim-pandoc#168]
vim-pandoc seems to crash with an error when attempting to navigate to certain headers, possibly ones that contain a period.

To reproduce, start with the following Markdown document:

```
# Header 1

## Header 1.1

- This is a link to [Header 2.1](#header-2.1)
- This is a link to [Header 2.3](#header-two-dot-three)
- This is a link to [Header 2.4a](#header-2.4a)
- This is a link to [Header 2.5](#header-2.five)
- This is a link to [Header 2.6](#header-2six)

# Header 2

## Header 2.1

## Header 2.2

## Header Two Dot Three

## Header 2.4

### Header 2.4a

### Header 2.five

### Header 2six
```

Position the cursor in a link that does not contain a period (e.g. the link to Header Two Dot Three) and type <Leader>gl. Pandoc moves the cursor to the header as expected.  It doesn't matter if the link text (in brackets) contains a period, but the link itself (in parentheses) must not contain a period.

Position the cursor anywhere in a link that contains a period (e.g. Header 2.1) and type <Leader>gl.  Pandoc crashes with the following error:

```
Error detected while processing /home/craig/.vim/bundle/vim-pandoc/autoload/pandoc/hypertext.vim:
line  294:
E127: Cannot redefine function pandoc#hypertext#OpenLink: It is in use
line  339:
E127: Cannot redefine function pandoc#hypertext#GotoID: It is in use
Error detected while processing function pandoc#hypertext#OpenLink..pandoc#hypertext#GotoID:
line   20:
E117: Unknown function: pandoc#hypertext#GotoSavedCursor
Press ENTER or type command to continue
```

I am using Vim 7.4.712 (apt-get install vim-gtk) under Ubuntu 15.10.  I'm using the master branch of Pandoc, currently commit c08a920.  I also tried running under the latest build of Vim (7.4.1752) and got the same results.

**Comment by alex-chew** [comment]
It looks like `pandoc#hypertext#GotoSavedCursor` was originally defined in commit b58d191, but was then deleted in commit 0d6458f. We could add it back, or simply remove the lone reference to it in `pandoc#hypertext#GotoID`.

**Comment by fmoralesc** [comment]
I think reintroducing it would be OK. I probably removed it as an oversight.

**Comment by fmoralesc** [comment]
Although, it's probably best to inline it, so we don't polute the `b:` variable namespace with something that is used only there.
