### ISSUE TITLE
replace :Pandoc by :make via :makeprg

### ISSUE THREAD

**Issue by Konfekt** [vim-pandoc/vim-pandoc#171]
How about replacing `:Pandoc` by `:make` via a file `~/.vim/compiler/pandoc.vim` with content

```vim
" Usage: compiler pandoc | silent lmake! % | lwindow | wincmd K

if exists("current_compiler")
  finish
endif

let current_compiler = "pandoc"

CompilerSet errorformat="%f",\ line\ %l:\ %m
CompilerSet makeprg=pandoc
```

Just because that's probably the way Vim means it to be.

**Comment by fmoralesc** [comment]
Because it is less flexible then. But I could add it if there is a need.

**Comment by Konfekt** [comment]
Oh, ok. The answer to https://gist.github.com/ajh17/a8f5f194079818b99199#gistcomment-1386030 made me think that `Vim` means to switch compilers by `CompilerSet`. But perhaps that's not a dogma, the advantages and inconveniences should be evaluated first.

**Comment by fmoralesc** [comment]
One issue with that is we can't define the tab-completion for the `:make` command, and also it would force us to be somewhat more verbose when invoking the command (`:Pandoc` has some shortcuts to make setting the output format simpler, for example; check the command-templates functionality for another feature it has in this sense). It's mainly an UX thing for me, but I'm not opposed to give some default value to the `makeprg` and `errorformat` settings.

**Comment by Konfekt** [comment]
Yeah, keeping `:Pandoc` as a convenient wrapper so to speak, and settings sensible defaults for the bare-bones `makeprg` and `errorformat` is the best of both worlds.

**Comment by fmoralesc** [comment]
Feel free to open an PR with the required changes ;)

**Comment by Konfekt** [comment]
Isn't `~/.vim/compiler/pandoc.vim` with content

```vim
" Usage: compiler pandoc | silent lmake! % | lwindow | wincmd K

if exists("current_compiler")
  finish
endif

let current_compiler = "pandoc"

CompilerSet errorformat="%f",\ line\ %l:\ %m
CompilerSet makeprg=pandoc
```
fine already?

**Comment by Konfekt** [comment]
Followed by
```vim
compiler latexmk
```
in `ftplugin/pandoc.vim`.

**Comment by fmoralesc** [comment]
Merged the PR.
