### ISSUE TITLE
Support for raw Latex

### ISSUE THREAD

**Issue by OolonColoophid** [vim-pandoc/vim-pandoc#178]
Hi there

I've been troubleshooting this all evening and haven't come to a satisfactory conclusion as to what's happening, but I'm wondering: is it the case that the formatting module prevents vim-pandoc from rendering raw latex? This appears to work via the standalone CLI utility but not via vim-pandoc. (Again, sorry I can't be more specific--I've been tweaking various things and no luck. The raw latex is simply passed through into the final doc as text.)

Any help very much appreciated.

Cheers

Ian

**Comment by fmoralesc** [comment]
Can you attach some sample text where this happens?

**Comment by OolonColoophid** [comment]
Thanks for the reply. I must apologise - I thought my script was using vim-pandoc, but I'm actually piping through to the command line version of pandoc itself.

**Comment by fmoralesc** [comment]
Ah, no problem.
