### ISSUE TITLE
cite autocompletion

### ISSUE THREAD

**Issue by zoltanpm** [vim-pandoc/vim-pandoc#185]
I'm trying to set a global .bib file for bibliography autocompletion, with the following in my init.vim:

let g:pandoc#biblio#sources = "g"
let g:pandoc#biblio#bibs = ['~/Dropbox/research_misc/zotero.bib']

This should, if I understand it correctly, allow me to use zotero.bib as a source for citekeys in any .md document. But when I try to create a citekey (with @name), no auto-completion window pops up.

I'm using Neovim stable (0.1.0), but have the deoplete plugin running -- is it possible that the plugin interferes with vim-pandoc's autocompletion here? Or is there some user error I'm not seeing?

**Comment by maccius** [comment]
If I remember right, at one time I had problems with pandoc-vim not seeing my bib file if I do not use absolute paths.  E.g. using ~ as shorthand for '/Users/<user>/Dropbox/...etc'.  You might try giving the full path, and see if that sorts the issue for  you.

**Comment by zoltanpm** [comment]
It doesn't -- the full path ['/Users/name.name/Dropbox/research_misc/zotero.bib'] doesn't help.

And it's even more vexing than that. I tried in on my home machine, with the exact same setup (init.vim is synced; same plugins), and it works. BUT: the path to the .bib on that machine is actually different [name_name instead of name.name], yet, even though init.vim gives it the wrong path on the home machine, it works.

I'm trying to wrap my head around how that's possible and report back.

**Comment by zoltanpm** [comment]
Unfortunately, full path doesn't work.

**Comment by maccius** [comment]
Sorry to hear that!  I just checked and I have my bib sources referenced just as you do in your example (but with full paths), and everything is working fine on my setup.  I don't have `g:pandoc#biblio#sources` explicitly set, though.  Does anything change if you comment that out?

**Comment by zoltanpm** [comment]
It was, as expected, user error. I'm so used to using Supertab plus deoplete for other types of auto-completion that I assumed the pop-up window would just appear (and it did, just not with with the bibtex content included). Once I disabled those plugins and forced myself to do it the manual way (ctrl-x ctrl-o), it worked.

**Comment by stfl** [comment]
Is it possible to configure deoplete to use the c-x c-o source input?

**Comment by stfl** [comment]
Ok I managed to trigger vim-pandoc's omnicompletion for bib through deoplete with following config:

```
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.pandoc= '@'
```

As I understood correctly, the only completion offered by vim-pandoc is for bibliography anyway, right? @vim-pandoc Is that correct?

**Comment by fmoralesc** [comment]
That is correct.

**Comment by stfl** [comment]
actually the following pattern is better, because it also matches when characters are present after the \@

    let g:deoplete#omni_patterns.pandoc= '@\w*'
