### ISSUE TITLE
Basic Pandoc command support without Python

### ISSUE THREAD

**Issue by dahanbn** [vim-pandoc/vim-pandoc#187]
I use Vim on multiple Windows PC without Python. Maybe you could consider a basic command (running pandoc on current file with in the settings specified output format) solution that doesn't need Python. 

That would be really helpful.

**Comment by AntoniosHadji** [comment]
One option you have is to use `:!pandoc %` to run pandoc outside of vim.  the % indicator refers to the current file.

**Comment by fmoralesc** [comment]
I just added some very minimal support for this.

**Comment by fmoralesc** [comment]
I think what we have already for the minimal case is enough.
