### ISSUE TITLE
Add support for Foldtext for emulated vim marker folds

### ISSUE THREAD

**Issue by kiryph** [vim-pandoc/vim-pandoc#199]
Consider following markdown snippet with a *html spoiler block*. I want to fold it. Since html block folding is not supported, I want to use emulated vim marker folding.
### Current behavior

```markdown
  <!-- {{{ -->
  <details><summary>Abstract</summary>
  *The invention is directed to...*
  </details>
  <!-- }}} -->
```
folds to
```markdown
  ##  <!-- {{{ --> / 12 lines / -----------
```
### Wanted behavior

```markdown
  <!-- Foldtext {{{ -->
  <details><summary>Abstract</summary>
  *The invention is directed to...*
  </details>
  <!-- }}} -->
```
folds to
```markdown
  ##  <!-- Foldtext --> / 12 lines / -----------
```

**Comment by fmoralesc** [comment]
I just included support for this, please confirm it works on your end.

**Comment by kiryph** [comment]
Thanks for the update. Yes, it works at my end as well. Just out of curiosity, what does `[m]` stands for?

**Comment by fmoralesc** [comment]
`[m]` stands for marker ;) Perhaps it's pointless to include it...

**Comment by kbro237** [comment]
I assume this is just what broke the functionality that I regularly used:

```
<!-- {{{ Notes
something here to hide
}}} -->
```

which used to name the fold 'Notes' but not just names it `[m]`.

Also the yaml fold at the top used to say `yaml` and now it doesn't. Actually, in one of my documents it says `[y]` and takes the value of the top field and in another it doesn't. Hm.

**Comment by fmoralesc** [comment]
@kbro237 I'll look into it. I changed the yaml code slightly, it might help if you can send me some examples of the headers causing trouble.

**Comment by kbro237** [comment]
@fmoralesc in my testing, it depends if `title` is the first key/value pair. E.g. 

```yaml
---
title: ok
author: me
---
```

is rendered as `- [y] ok / 4 lines / --------` while

```yaml
---
author: me
title: ok
---
```

is rendered as `- ## --- / 4 lines / ------`

My `foldmethod` is set to `manual`. I don't know if I did that or if vim-pandoc does that. Also, this isn't a big deal for me...the way I use comments as noted above has a bigger impact.
