### ISSUE TITLE
How to disable header count and folding symbols in the gutter?

### ISSUE THREAD

**Issue by Cutuchiqueno** [vim-pandoc/vim-pandoc#200]
Some time ago vim-pandoc puts characters in the gutter which highlight if there is fold that can be opened or closed ('+-') or inform about the header level the cursor is in by showing the level number.

Is it possible to disable this?
Is it possible to change the characters that are used?

I apologize in advance because I am sure there is a config option I have missed but I could not find it in the documentation.

**Comment by lgalke** [comment]
Hey @Cutuchiqueno,

The relevant option is `foldcolumn` and is set according to `g:pandoc#folding#fdc` in vim-pandoc.
Setting the latter (plugin-specific) option to `0` in your vimrc should disable the fold column.
The characters are not that easy to change as far as I know. You may have a look at `:h folding` and `:h foldcolumn`. The design of the foldcolumn is unrelated to vim-pandoc. 

Hope I could help.

Best Regards,
Lukas

**Comment by Cutuchiqueno** [comment]
Hi @lgalke 
thank you, that helped me to sort out what relates to waht
