### ISSUE TITLE
Suggestion: add pandoc as the formatprg

### ISSUE THREAD

**Issue by Alok** [vim-pandoc/vim-pandoc#201]
I realized that you can use pandoc to format markdown with the following command:

```vim
setlocal formatprg=pandoc\ -f\ markdown+autolink_bare_uris\ -t\ markdown+autolink_bare_uris\ --atx-headers
```

The `autolink` is to avoid escaping bare URLs, the ATX headers is personal preference. I usually then run it through `sed` to avoid adding backslashes to square brackets because `pandoc` does not recognize checkboxes like GitHub markdown does.

You might want to consider adding `pandoc` as the `formatprg` for the pandoc filetype.

**Comment by fmoralesc** [comment]
Implemented a version of this.
