### ISSUE TITLE
find_bibfiles should respect "bibliography" YAML header

### ISSUE THREAD

**Issue by manuelkappler** [vim-pandoc/vim-pandoc#207]
Apologies if this issue already came up.

- Issue: WIth the bibliography module enabled, random JSON files in the same directory get passed to pandoc as bibliography sources *even if* there is a bibliography given in the YAML header.
- Expected behavior: Pandoc itself parses the YAML header and finds the bibliography file from there. 
- Possible solution: in `vim_pandoc.bib.find_bibfiles()` add code to check for a bibliography file in the YAML header and use that file (skip all other collation). I could implement that, but I wasn't sure whether there is any existing YAML-parsing code that I'd need to respect. If you can let me know, I'll fiddle with it and make a PR later.

BTW, thanks for all the work on this extension, real life-saver!

**Comment by fmoralesc** [comment]
(Sorry for the late response, I've been busy on other things.)

I don't use YAML headers, so that's the reason for this omission. Looks like a nice idea. There isn't YAML parsing code at all, so if you can take a look at it go ahead (your guess is correct as to where those changes would be needed). If not, I'll try to look into it ASAP.

(Also, thanks for your words! :))

**Comment by fmoralesc** [comment]
I just added the ability to use a bibliography specified in the YAML header as a source. Please test if it works for you.

**Comment by manuelkappler** [comment]
Thanks for the quick attempted fix!
I tried to make your changes work, but (and this is presumably something on my end, but I can't figure out what it is) when loading a markdown file I now get the following errors:

`Error detected while processing function pandoc#bibliographies#Init:`
`line 34`
`E121: Undefined variable: bibliography`
`E116: Invalid arguments for function add`

I already tried a few things I could think of (for example, in `bibliographies.vim` you access the bibliography key with `[bibliography]`, I tried to substitute that with `['bibliography']` and `.bibliography`, which both won't work. I also looked over all your code and I can't seem to figure out where the error could come from :(

I'm unfortunately not well-equipped to do debugging in vimscript (I tried to output some messages from the plugin, but couldn't get that to work — it seems like I don't understand what `echom` does), and my attempts at using the debugger and log-files didn't yield anything either.

I'll have to work on other things right now, but I'll try to have another look over the weekend. If you have any ideas what could be causing the error, feel free to let me know ;)

**Comment by fmoralesc** [comment]
I had a similar issue yesterday, but i thought I had fixed it already. I can't reproduce it locally, sadly. Can you send me the YAML header of the file causing this? Perhaps I am not escaping things right for the input.

Meanwhile, you can workaround putting the `add` call inside a try...catch struct

``` vim
try
     call add(b:pandoc_biblio_bibs, b:pandoc_yaml_data['bibliography'])
catch
endtry
```

**Comment by manuelkappler** [comment]
No, you were right. I thought I had updated the files with a git pull, and your changes were there, but after running PlugUpdate it suddenly worked and now processes my bibliography properly. Apologies and again, many thanks!

**Comment by fmoralesc** [comment]
Great, then! I was thinking I needed to overhaul the whole thing! 😰
