### ISSUE TITLE
triggering equalprg conflict in completion mode

### ISSUE THREAD

**Issue by kbro237** [vim-pandoc/vim-pandoc#208]
As of latest commit (`d77898`) there is a conflict with vim-pandoc: when I try to complete a word (e.g. with `<C-N>`) the equalprg command runs. I thought it was a conflict with neocomplete, but I disabled that plugin and it persists. It only effects documents when the filetype is set to `pandoc`.

When I roll the plugin back to `b06191f`, the problem goes away.

**Comment by BonarBeavis** [comment]
Same with ycm and the rollback helps too.

**Comment by fmoralesc** [comment]
Does this problem persist if the `indent` module is blacklisted?

**Comment by BonarBeavis** [comment]
With `intend` blacklisted it is fine.

**Comment by fmoralesc** [comment]
Two questions: what are the value of `&indentexpr` when it works and when it fails to work? Does the issue happen also if you execute `runtime! indent/tex.vim` (without enabling the `indent` module)?

**Comment by BonarBeavis** [comment]
1. Empty when it works
2. When it fails: `pandoc#indent#GetIntend()`
3. Does still happen.

**Comment by fmoralesc** [comment]
Ok, then, it's the tex indentation file we source that it's causing the issue. It would be interesting to see if the problem happens to you if you edit a tex file and try to use make a completion, but I imagine it would.

As a workaround, I disabled the `indent` module by default.

**Comment by BonarBeavis** [comment]
Found the culprit, it is LatexBox.

```
Executing CompleteDone Auto commands for "<buffer=3>"
autocommand call Latexbox_CallIndent()

line 0: call Latexbox_CallIndent()
calling function Latexbox_CallIndent()

line 1:   " Save the current cursor position.
line 2:   let cursor = getpos('.')
line 3: 
line 4:   " Save the current window position.
line 5:   normal! H
line 6:   let window = getpos('.')
line 7:   call setpos('.', cursor)
line 8: 
line 9:   " Get first non-whitespace character of current line.
line 10:   let line_start_char = matchstr(getline('.'), '\S')
line 11: 
line 12:   " Get initial tab position.
line 13:   let initial_tab = stridx(getline('.'), line_start_char)
line 14: 
line 15:   " Execute the command.
line 16:   execute 'normal! =='
line 16: normal! ==
line 16: .!pandoc --atx-headers -t markdown+table_captions+backtick_code_blocks+tex_math_dollars+pipe_tables-simple_tables+fenced_code_attributes --wrap=auto --columns=79 
```

This [autocommand](https://github.com/LaTeX-Box-Team/LaTeX-Box/blob/master/indent/tex.vim#L132) triggers the [formating](https://github.com/LaTeX-Box-Team/LaTeX-Box/blob/master/indent/tex.vim#L111)

**Comment by fmoralesc** [comment]
[My question is... *why* does it need to do that?] 

I could disable the module depending on whether the autocommand exists or I could disable the autocommand if present. Don't know what is the best approach.

**Comment by kbro237** [comment]
Good catch, @BonarBeavis. Disabling the autocommand is preferable for me since I forgot that Latex-Box was even being sourced -- I rarely work in tex files directly now.

**Comment by fmoralesc** [comment]
OK, I'll go with that.
