### ISSUE TITLE
Citation autocomplete not working

### ISSUE THREAD

**Issue by tpoisot** [vim-pandoc/vim-pandoc#210]
Here is `vim --version` (relevant lines)

~~~
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 19 2017 13:44:53)
Included patches: 1-206
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
~~~

I have a file `file.md` and a list of references `file.json`, and my `.vimrc` is

~~~ vimrc
let g:pandoc#biblio#sources = "bcg"
let g:pandoc#completion#bib#mode = "fallback"
~~~

When I type in `@p` and then `Ctrl-X Ctrl-O`, nothing happens. Is there a way for me to see if the json file is read at all?

**Comment by fmoralesc** [comment]
You can use `echo pandoc#bibliographies#Find_Bibliographies()`.

**Comment by tpoisot** [comment]
The correct file is detected.

**Comment by fmoralesc** [comment]
Can you change lines 107-111 in `pythonx/vim_pandoc/bib/fallback.py`

``` python
    try:
        data = json.loads(text)
    except:
        return entries
```
into 
``` python
    data = json.loads(text)
```
It's possible that there is some issue when loading the json data.

**Comment by tpoisot** [comment]
Tried, not working.

**Comment by fmoralesc** [comment]
Did it throw an exception?

**Comment by tpoisot** [comment]
No, no exception.

**Comment by fmoralesc** [comment]
In that case, after that line, add
```
print(data)
```

If it prints a dict, then that means the problem is somewhere in what remains of that function. If not, the problem is in the way it is reading the file and passing the data to it.

**Comment by fmoralesc** [comment]
(Sorry to ask you these things, I don't have a json bibliography file to test here myself. You could send me one if it's too much trouble to debug it along me.)

**Comment by tpoisot** [comment]
It's not printing anything

**Comment by tpoisot** [comment]
Interestingly, this json file is not working with citeproc either. But it's accepted by pandoc-citeproc.

**Comment by fmoralesc** [comment]
Ok, then. In this case, check if the file is being read and passed to the json parser. change the else clause in line 150 into

``` python
            elif bib_type == "json":
                print(bib)
                print(text[:20])
                ids = get_json_suggestions(text, self.query)
```

**Comment by tpoisot** [comment]
No, not printing anything -- here is the file, https://gist.github.com/tpoisot/ebf13e9cc07e387d34e94a43e3c0918a

**Comment by fmoralesc** [comment]
If after this change nothing is printed, then the `find_bibfiles()` function in `SourceCollator` is what's causinjg the problem (the file isn't detected, perhaps the path has special characters?). Specially if you say that the citeproc mode is not working either.

**Comment by fmoralesc** [comment]
Very odd. It is detected here when I use any of the `citeproc` and `fallback` backends, and I get completions.

**Comment by tpoisot** [comment]
Ok, so it's a conflict between packages. Let me a few moments to figure out which one is guilty.

**Comment by tpoisot** [comment]
Gotit, it's `julia-vim` by @JuliaLang -- I'll open an issue there.

**Comment by fmoralesc** [comment]
Ah! Is it because of the Latex-to-Unicode functionality?

**Comment by tpoisot** [comment]
Yes -- when it's active for all filetypes, it seems to have some side effects on what <Tab> does.

**Comment by fmoralesc** [comment]
Let me know if you can find a workaround. I was working on something similar but somewhat more limited in scope some weeks ago, and that doesn't use the completion system: https://github.com/fmoralesc/nvim-logic
