### ISSUE TITLE
Error at start in MacVim

### ISSUE THREAD

**Issue by odhondt** [vim-pandoc/vim-pandoc#212]
I have installed the plugin with Vundle.
When I start MacVim on OSX Yosemite, I get the following error:
Error detected while processing /Users/oliv/.vim/bundle/vim-pandoc/ftplugin/pandoc.vim:
line    1:
E488: Trailing characters: <<<<<<< HEAD
line  217:
E488: Trailing characters: =======
line  244:
E488: Trailing characters: >>>>>>> e2e0ec879c7cc9acc7ecaea10db837696161dbab
line    1:
E488: Trailing characters: <<<<<<< HEAD
line  217:
E488: Trailing characters: =======
line    1:
E488: Trailing characters: <<<<<<< HEAD
line  217:
E488: Trailing characters: =======

**Comment by fmoralesc** [comment]
I recommend you reinstall the plugin, Vundle seems to have messed up with the file somehow.

**Comment by odhondt** [comment]
It worked, thanks!
