### ISSUE TITLE
pandoc-syntax as git submodule

### ISSUE THREAD

**Issue by sim590** [vim-pandoc/vim-pandoc#213]
> vim-pandoc doesn't provide syntax support. The user needs to install vim-pandoc/vim-pandoc-syntax alongside it (see below). The reason for this is we have found cleaner to keep the bug tracking of the syntax file and the rest of the system separate.

Why not include vim-pandoc-syntax as git submodule? The way I see it, it could be as easy as adding the subdirectory in the runtime path much like plugin managers do.

**Comment by fmoralesc** [comment]
Given the fact that people still submit issues about the syntax file here, I might reconsider whether the current approach is right. However, I tend to think using submodules would be needlessly complicated (imho), and at any rate the syntax file is supposed to be optional (although a lot of the functionality here depends on it). So dunno...

**Comment by doronbehar** [comment]
Many people use git's submodules on their tracked dotfiles repositories and on their tracked personal Vim configuration. IMHO, adding a 2nd layer (which is a 3rd/4th layer for some users) to the structure might make things more complicated in the future.

For example: What if someone would like to use the stock markdown syntax file and only use the commands this submodule gives? Will the suggested structure will force these users in any way to use the `vim-pandoc`'s syntax submodule?

Just thinking out loud..

**Comment by fmoralesc** [comment]
I think now that this does not add any benefit and as mentioned above, complicates things needlessly.

**Comment by alerque** [comment]
Using submodules would definitely interfere with many vim plugin managers and dotfile systems. It might make life better for a few very specific arrangements but I think on balance it would be a net negative. Agree with closure as `wontfix`.
