### ISSUE TITLE
No details of compile error is shown with PDF export

### ISSUE THREAD

**Issue by maxigaz** [vim-pandoc/vim-pandoc#214]
Take, for example, a .md file that contains the following text (I deliberately wrote "\latex" instead of "\LaTeX" to produce an error here):

```
Hello \latex
```

When I try to export this to PDF using `pandoc --latex-engine=xelatex -o "test.pdf" "test.md"` from the terminal or as an ex command (preceded by `:!`), I get a detailed error message:
```
! Undefined control sequence.
l.60 Hello \latex

pandoc: Error producing PDF
```

However, when I use `:Pandoc pdf` in Neovim 0.1.7, I can only see the following, which is not very helpful when it comes to debugging long files:

```
# Press q to close this
> pandoc --latex-engine=xelatex -o "test.pdf" "test.md"
```

**Comment by fmoralesc** [comment]
I am aware. For neovim, I don't have a way to gather `pandoc`'s output yet.

**Comment by fmoralesc** [comment]
Just pushed a fix, can you test if it works for you now?

**Comment by maxigaz** [comment]
Yes, it works now with your change. Thank you very much!
