### ISSUE TITLE
Do not mess around user's 'foldtext'

### ISSUE THREAD

**Issue by zhou13** [vim-pandoc/vim-pandoc#217]
I have my perfect `foldtext()` set in my vimrc.  However pandoc tries to override it by setting
```
setlocal foldtext=pandoc#folding#FoldText()
```
for me, which gives me an inconsistent vim experience.

**Comment by fmoralesc** [comment]
You can disable this with
```
let g:pandoc#folding#use_foldext = 0
```

**Comment by Konfekt** [comment]
This could also be achieved by adding `setlocal foldtext<` to `~/.vim/after/ftplugin/pandoc.vim`.
