### ISSUE TITLE
pandoc filetype swallowing comments on template file expansion

### ISSUE THREAD

**Issue by Konfekt** [vim-pandoc/vim-pandoc#218]
With the plugins https://github.com/aperezdc/vim-template and the plugin 'https://github.com/vim-pandoc/vim-pandoc' installed, the template file `=template=makefile` with content
```make
NAME=main
FILES=%HERE%
DEP=$(NAME).pandoc $(FILES)

# vim:ft=make
```
produces, when calling `vim makefile`, the following file:
```make
NAME=main
FILES=%HERE%
DEP=$(NAME).pandoc $(FILES)
```
That is, the comment disappears. In fact, if the comment is not placed at the beginning of the file, all lines below it won't appear when the template is expanded.

This is a cross-post from https://github.com/aperezdc/vim-template/issues/115

**Comment by fmoralesc** [comment]
How does this work, at all? I can't grasp the steps. The `makefile` file shouldn't be handled by vim-pandoc, and nothing in this chain seems like it would trigger it.

**Comment by aperezdc** [comment]
Author of `vim-template` here. Expanding templates uses a series of substitutions, and it matches exactly the few expansions supported: i.e it replaces only the `%HERE%` literal, it does not try to do any fancy matching.

**Comment by aperezdc** [comment]
Mmh, now that I think of it, I wonder whether there could be something wrong in the logic around `l:deleteLastLine`, at [templates.vim:453](https://github.com/aperezdc/vim-template/blob/master/plugin/templates.vim#L453).

@Konfekt: Can you trying adding an empty line as last line of your template and reporting whether that “works”?

**Comment by Konfekt** [comment]
Yep, this fixes it!

**Comment by fmoralesc** [comment]
OK, then. I'm closing this here. Leave it to you, @aperezdc! ;)
