### ISSUE TITLE
:Pandoc pdf fails with Python AttributeError

### ISSUE THREAD

**Issue by hbhargava7** [vim-pandoc/vim-pandoc#224]
Attempting to run :Pandoc! pdf with a markdown file open leads to the following error:

```
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hbhargava/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 224, in __call__
    output_format = c_args.pop(0) if len(c_args) > 0 and self.opts.in_allowed_formats(c_args[0]) else "
html"
  File "/Users/hbhargava/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 185, in in_allowed
_formats
    if not identifier.startswith("markdown") and identifier in PandocHelpParser.get_output_formats_tabl
e():
  File "/Users/hbhargava/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 134, in get_output
_formats_table
    for i in PandocHelpParser._get_output_formats():
  File "/Users/hbhargava/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 129, in _get_outpu
t_formats
    return wrap_formats(get_raw_pandoc_data("Output formats:(.*)\[\*+for pdf"))
  File "/Users/hbhargava/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 74, in get_raw_pan
doc_data
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
I have updated to the latest version of vim-pandoc. The document I am attempting to run the command on is a .md file. This is the first time I have tried to use the plugin, though, so it could be an issue with my installation.

**Comment by fmoralesc** [comment]
Hi! Can you provide me with the output of `pandoc --version`? `vim-pandoc` is trying to get the formats that `pandoc` supports, and that depends on the version (< 1.18, we tried to parse the output of `--version`, and after that, we call `pandoc --list-output-formats`, which is more robust. It seems that `vim-pandoc` detected an older version and the data is not retrieved properly.

**Comment by hbhargava7** [comment]
Thanks for the quick response! Here is the output of pandoc --version
```
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/hbhargava/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by fmoralesc** [comment]
That's (almost) the same version as me. 

Are you using the vim-pandoc version from master? If you are, the `pythonx/vim_pandoc/command.py` file should contain `if get_pandoc_version() >= '1.18':`, not `if get_pandoc_version() == '1.18':`.

**Comment by fmoralesc** [comment]
Also, changing that should fix the issue, but it's better to update to master if possible.

**Comment by hbhargava7** [comment]
You nailed it - the problem was that I have vim-pandoc loaded as a git submodule and I didn't realize that `git submodule update` doesn't actually update the submodules (`git submodule foreach git pull` is needed). 

Thanks for your time and maintaining a great plugin!

**Comment by fmoralesc** [comment]
Thanks for the kind words! It's no problem.

**Comment by vvizzo** [comment]
Hello, got identical error

Trying to do :Pandoc html

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 238, in __call__
    and self.opts.in_allowed_formats(c_args[0]) \
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 188, in in_allowed_formats
    if not identifier.startswith("markdown") and identifier in PandocHelpParser.get_output_formats_table():
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 137, in get_output_formats_table
    for i in PandocHelpParser._get_output_formats():
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 132, in _get_output_formats
    return wrap_formats(get_raw_pandoc_data("Output formats:(.*)\[\*+for pdf"))
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 77, in get_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

with newest pandoc:
pandoc.exe 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: C:\Users\Mikolaj\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

and newest vim-pandoc. Line mentioned earlier is with >=

TIA

m.

**Comment by jloow** [comment]
I can add that I can convert to HTML fine, but converting to pdf fails with the same error.
