### ISSUE TITLE
pantondoc#folding#MarkdownLevelSA is _very_ slow

### ISSUE THREAD

**Issue by blaenk** [vim-pandoc/vim-pandoc#23]
So lately I've had some time to update some stuff on my site again and I noticed that typing is ridiculously slow, to the point where it freezes up every 2-3 seconds and then ~10 words I typed appear, and this repeats. I was `git reset`ing to previous commits one by one in vim-pandoc-syntax and found that commit [3bfa541a168e097db1ee7e34caf12452a3ce9be0](https://github.com/vim-pandoc/vim-pandoc-syntax/commit/3bfa541a168e097db1ee7e34caf12452a3ce9be0) in vim-pandoc-syntax triggered this. I then cross-referenced it in this project which is where I figured it was being checked for and I noticed it's used to determine whether or not to use the syntax-assisted foldexpr function `pantondoc#folding#MarkdownLevelSA`.

I'm not sure what can be done to improve the performance of this function. It includes a lot of branches, string/regex compares, and syntax attribute fetching. I was wondering though, since we're using manual syntax checking, why not just use `fold-syntax` with the `foldmethod` option? The `syn-fold` help section shows this:

``` vim
syn region myFold start="{" end="}" transparent fold
syn sync fromstart
set foldmethod=syntax
```

Then we can simply add the `fold` to header syntax groups? I imagine you have a reason for not having done that, but in case it slipped past you or something. If we don't switch to using that entirely, then perhaps we can switch to using that if `g:vim_pandoc_syntax_exists`? Just some ideas. Right now for me the folding renders everything unusable since it really hinders my typing speed.

**Comment by keyofnight** [comment]
This still seems problematic. I ran profiling in my own slow-down tests. In a 70 line file with about 10 headers, I typed in "This is a test." (This was difficult, as I incurred significant lag.) I then pressed `u` to undo. (Which took about 5 seconds to complete.) Then I pressed `<ctrl>+r` to redo. (This took another 5 seconds to complete.) Here are the results of my profiling.

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
46027  10.645650   4.947086  pandoc#folding#FoldExpr()
46027   5.698564             pandoc#folding#MarkdownLevelSA()
   11   0.001116   0.000963  pandoc#folding#FoldText()
    6   0.000701             <SNR>23_Highlight_Matching_Pair()
    9   0.000162             lightline#link()
   11   0.000153             pandoc#folding#MarkdownFoldText()
    9   0.000060             lightline#mode()
    4   0.000057             lightline#update_once()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
46027              5.698564  pandoc#folding#MarkdownLevelSA()
46027  10.645650   4.947086  pandoc#folding#FoldExpr()
   11   0.001116   0.000963  pandoc#folding#FoldText()
    6              0.000701  <SNR>23_Highlight_Matching_Pair()
    9              0.000162  lightline#link()
   11              0.000153  pandoc#folding#MarkdownFoldText()
    9              0.000060  lightline#mode()
    4              0.000057  lightline#update_once()
```

I have the FastFold plugin installed and I've tried `let g:pandoc#folding#fastfolds = 1` and `let g:pandoc#folding#fastfolds = 0`. I've also tried removing all plugins beside vim-pandoc. For now, the only real solution for me is to disable folding, but I'm not sure I've ever been able to use folding without a significant performance hit.
