### ISSUE TITLE
Pandoc latex-engine option changed to pdf-engine

### ISSUE THREAD

**Issue by raymondEhlers** [vim-pandoc/vim-pandoc#236]
As noted in the changelog [here](https://github.com/jgm/pandoc/commit/1cd2d0475008ab74fca54a2b30f145caaf877a68#diff-6b306396aa9fdbc560492611d41dd56f), pandoc recently changed the option `latex-engine` to `pdf-engine`. So the options need to be updated for pdf and beamer.

I applied a rather trivial fix on my own fork [here](https://github.com/raymondEhlers/vim-pandoc/commit/8e719a297ae56280e185c64710c767285bb4c39b), but you may want a more careful fix. If you're happy with mine, I'm happy to create a PR.

**Comment by fmoralesc** [comment]
I just committed some changes that should take care of this. One thing left to take care of is that templates which used `--latex-engine` (I had a few, don't judge) need to be adjusted manually for now. I'm not sure if I want to 'correct' the templates on expansion or not.

**Comment by raymondEhlers** [comment]
Thanks! Your fix resolves the issue for me

**Comment by schanzel** [comment]
Works for me. Tested with Pandoc 2.0.1.1

Many thanks!
