### ISSUE TITLE
Error when running Pandoc pdf

### ISSUE THREAD

**Issue by PabloLeon** [vim-pandoc/vim-pandoc#239]
Hi! Thanks for this great plugin...Unfortunately I cannot get compilation to work. When I run Pandoc pdf (or other output) I get: 
Error detected while processing function pandoc#command#Pandoc:line 5:Traceback (most recent call last):File "<string>", line 1, in <module>File "/home/pablo/.vim/plugged/vim-pandoc/pythonx/vim_pandoc/command.py", line115, in __call__self._run_command = " ".join(arglist)TypeError: sequence item 0: expected str instance, bytes found

I have VIM8 (Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 20:13:43), Included patches: 1-197, 322, 377-378, 422, 550 ) and pandoc 2.0.2 installed and my vim has python3 support.

Any ideas? I can compile using pandoc in the cli just as expected.

**Comment by PabloLeon** [comment]
I've switched to neovim and it works - I susptect it was was some anaconda virtualenvironment vs os python libraries messup.

**Comment by fmoralesc** [comment]
In some cases vim's and neovim's python's modules send data around under different types (vim sends strings, neovim sends bytes). What version of python vim uses will matter as well.

In this case, I didn't test it in vim, so this is the result of an oversight. These days I test the plugin with neovim.
