### ISSUE TITLE
setting --output as a user

### ISSUE THREAD

**Issue by kwibus** [vim-pandoc/vim-pandoc#243]
i used to be able to pass --output file/path to :Pandoc and it respected it.
Now, after some updates the the plugin decide output directory.
now i am wondering:

* Is this intentional?
* can you suggest a way to set output directory? 
(I can otherwise call pandoc myself, is this still a great plugin)
* otherwise could you implement this in the future?

**Comment by fmoralesc** [comment]
This is an oversight in the recent refactor, I have a fix in the py-refactor branch.
