### ISSUE TITLE
Error detected while processing function pandoc#bibliographies#Init[40]..provider#python3#Call:

### ISSUE THREAD

**Issue by doronbehar** [vim-pandoc/vim-pandoc#244]
```
line 18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: bad magic number in 'vim_pandoc': b'\x03\xf3\r\n'
```
The error occurs when opening every markdown file. There is no flaw in the behaviour of the plugin besides that (not that I'm aware of) but it is sort of annoying..

Thanks.

**Comment by fmoralesc** [comment]
[This](https://stackoverflow.com/a/514395) suggests that perhaps the `.pyc` files generated by the python interpreter (in the `__pycache__` folder perhaps) might have become damaged, you could try deleting them. No clue what might be causing this.

**Comment by doronbehar** [comment]
Thanks, that worked!

**Comment by ybryan** [comment]
For anyone that comes across this issue on Mac. If you are using `homebrew` and upgrade vim (or macvim in my case) with python3 support and upgrade to python3.7 this exact issue will occur. Downgrade your python3 to 3.6 (some issue with versioning https://github.com/Yggdroot/LeaderF/issues/138) and brew with only support for python2

`brew switch python 3.6.4`
`brew install macvim --with-python@2 --with-override-system-vim`
