### ISSUE TITLE
Multiple errors: `:Pandoc` and `omni-completion` failure on VIM, but *not* NVIM

### ISSUE THREAD

**Issue by maccius** [vim-pandoc/vim-pandoc#246]
I have encountered a strange problem with the `vim-pandoc` plugin.  Specifically, I can not get e.g. `:Pandoc` or `omni-completion` (bibliography completion) functions to work at all.  If `:Pandoc` is called, it simply fails to compile or register any message.  If called as `:Pandoc!`, I receive the error `E477: No ! allowed`.  Similarly, if I try to use `omni-completion` to e.g. fill out a citation, I receive the error `Pattern not found`, even when all files are properly loaded, and `@` reference tags are already present.

What is strange is that these issues crop up *only* with my mainline VIM/MacVIM installations, but *not* with NVIM/VimR.  Both of those work perfectly, and function exactly as I would expect them to.  Moreover, I know that my MacVIM installation *used* to work perfectly with `vim-pandoc`, as I used the system extensively a month or so ago.  (I haven't been using it for a while.)

In trying to figure this problem out, I have done the following, without success:
* Completely uninstalled and reinstalled all versions of VIM and MacVIM, using both pre-built binaries and building from source.  I am using the newest stable 8.x versions of both.
* Tried re-installing/running older 7.4.x versions of MacVIM and VIM.
* Completely uninstalled and reinstalled all Python installations and `pyenv` environments.
* Worked through my `.vimrc` in order to isolate the problem, while also working through relevant FAQs and configuration guides for all the various elements.
* Tried installing different versions of Python (v2/v3), and also verifying that my VIM installations can see the installation.  (Both return `1` for `:echo has("python")`). 
* Anything else I can think of...

I would appreciate any help that you can give, because I am totally baffled.  I would like to figure out the problem, because I have found that MacVIM handles the `vim-pandoc-syntax` highlighting much more smoothly than NVIM/VimR does.

**Comment by maccius** [comment]
Okay, I think that I may have found the problem.  It looks like `vim-pandoc` moved (maybe entirely?) to Python 3 a few weeks ago.  So far as I can tell, the neither the binary releases of MacVIM nor the Homebrew versions (even build from `--HEAD`) have Python 3 support built in.  I had both Python 2 and Python 3 installed and available, but the current version `vim-pandoc` now only makes Python 3 calls.  I reinstalled MacVIM using `--with-python3`, and all functions and features now seem to work properly.

It might be worth putting a note in the documentation to indicated that Python 3 is required?  Currently it advises checking `:echo has("python")`, but should ask to check `:echo has("python3")`.

**Comment by fmoralesc** [comment]
Thanks for the reminder. Yes, python 3 is now a hard requirement.
