### ISSUE TITLE
how to avoid that first and second level headers are autoformatted 

### ISSUE THREAD

**Issue by kraxli** [vim-pandoc/vim-pandoc#247]
Hi 

is there a way to avoid that first and second level headers are autoformatted (by ```=``` command)
from ```# header 1``` to 

```header 1```
```========```

and from ```## header 2``` to 

```header 2```
```--------```
?

Many thanks!

**Comment by fmoralesc** [comment]
vim-pandoc uses `pandoc` for `=`, and if I'm reading https://pandoc.org/MANUAL.html#options-affecting-specific-writers correctly, it should do what you want by default. What is the value of `g:pandoc#formatting#equalprg` and `g:pandoc#formatting#extra_equalprg` in your config?

**Comment by kraxli** [comment]
many thanks for the quick reply! I did not set the two values and so expect that they are set to the default values:
```
- *g:pandoc#formatting#extra_equalprg*
  default = "--reference-links"
```
and 
```
- *g:pandoc#formatting#equalprg*
  default = "pandoc -t markdown [--columns {g:pandoc#formatting#textwidth}|--wrap=none]"
```

**Comment by fmoralesc** [comment]
Ah, sorry, I misunderstood. You can do this adding

``` vim
let g:pandoc#formatting#extra_equalprg = "--reference-links --atx-headers"
```
to your config.

**Comment by kraxli** [comment]
Many thanks! Exactly what I was looking for :-)
