### ISSUE TITLE
':Pandoc!' and other commands fail

### ISSUE THREAD

**Issue by hbhargava7** [vim-pandoc/vim-pandoc#248]
Suddenly several things have stopped working (not sure what changed, maybe an update). I'm running the latest version of Vim from homebrew, and I just re-cloned vim-pandoc. 

Running `:Pandoc pdf` (for instance) has no effect. When I press enter, the command just stays in the bar and nothing happens.

Running `:Pandoc! pdf` yields the error "E477: No ! allowed".

The only thing that seems to be working is `:Pandoc -o test.html`. But the command doesn't clear from the bar (not sure if it used to).

Nothing is reported in `:messages`.

Any help would be appreciated!

**Comment by fmoralesc** [comment]
We recently moved from a python2/3 hybrid arch to a pure python3 one. Does your vim have python3 support? If not, that would explain it, because in that case the `:Pandoc` command degrades (this is not thoroughly tested, I admit, so that is probably why you are having these issues).

**Comment by hbhargava7** [comment]
Just reinstalled Vim using `brew install vim --with-python3` and things are working. Thanks!
