### ISSUE TITLE
E492: Not an editor command: Pandoc

### ISSUE THREAD

**Issue by dnebauer** [vim-pandoc/vim-pandoc#251]
I use filetype `markdown` and have set variables `g:pandoc#filetypes#handled` and `g:pandoc#filetypes#pandoc_markdown` to enable vim-pandoc for filetype `markdown` according to the install instructions.

After loading a markdown file here are some relevant variable values:

```vim
:echo &ft
markdown
:echo g:pandoc#filetypes#handled
['pandoc', 'markdown']
:echo g:pandoc#filetypes#pandoc_markdown
0
:echo g:pandoc#modules#enabled
['formatting', 'folding', 'command', 'keyboard', 'bibliographies', 'yaml', 'completion', 'toc', 'chdir', 'hypertext']
:echo g:pandoc#modules#disabled
[]
```

However, when I try to execute `Pandoc` I get:

```vim
:Pandoc
E492: Not an editor command: Pandoc
```

If I manually set filetype to `pandoc` as you advised in #152 it does set the command `:Pandoc` and fix the problem, but I thought my configuration should set the command `:Pandoc` for filetype `markdown`.

Using pandoc 2.0.5. Tested on vim 8.0 and nvim 0.2.2.

**Comment by dnebauer** [comment]
Well, I couldn't fix the problem so I worked around it by changing the filetype to `markdown.pandoc`.

**Comment by fmoralesc** [comment]
Sorry I didn't answer before, I still have to test in what conditions this can rise. I think the current setup is probably too complicated :/
