### ISSUE TITLE
:Pandoc command fails

### ISSUE THREAD

**Issue by alefa** [vim-pandoc/vim-pandoc#255]
When trying to convert a simple markdown file (just a bit of text saved as "Test.md") to another format using a command like `:Pandoc pdf`, I get the following error message:

```
Error detected while processing function pandoc#command#Pandoc[5]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gita/.config/nvim/plugged/vim-pandoc/python3/vim_pandoc/command.py", line 51, in __call__
    p = self.pandoc_info.build_argument_parser()
  File "/home/gita/.config/nvim/plugged/vim-pandoc/python3/vim_pandoc/helpparser.py", line 118, in build_argument_parser

    parser.add_argument(*flags, **extra)
  File "/usr/lib/python3.5/argparse.py", line 1353, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1716, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1557, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1367, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.5/argparse.py", line 1506, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.5/argparse.py", line 1515, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -o/--output: conflicting option string: -o
```
I have no idea what is causing this error. I've tried running the command in Neovim with a minimal init.vim which only loads the vim-pandoc plugin and got the same error. Converting documents on the commandline outside of Vim works fine. The vim-pandoc command also worked for me not long ago, and I don't remember changing anything in the meantime. I'm running vim-pandoc (most recent version installed using vim-plug) in Neovim 0.2.2 on Debian Stretch. The latest version of python3-neovim is installed. My pandoc version is 1.17.2.
Would be grateful for help with this issue.

**Comment by fmoralesc** [comment]
It is because of some incompatibility with that version of pandoc. If possible, I would recommend to update it (latest is 2.0.6). Otherwise, you could try reverting to https://github.com/vim-pandoc/vim-pandoc/commit/0687b9972bd2d3bf2355c0bce7936387ea57de43 and see if that solves the issue.

**Comment by fmoralesc** [comment]
Actually, the latest pandoc is 2.1.1

**Comment by alefa** [comment]
Thanks for the fast reply! I just installed the latest version (2.1.1) from the project website. Everything works now.

**Comment by nirvana6** [comment]
I almost encounter the same error with @alefa . 
```shell 
"reopenBlog.md" 36L, 1531C                                                                                                                    
Error detected while processing function pandoc#bibliographies#Init[40]..provider#python3#Call:                                               
line   18:                                                                                                                                    
Traceback (most recent call last):                                                                                                            
  File "<string>", line 1, in <module>                                                                                                        
ImportError: bad magic number in 'vim_pandoc': b'\x03\xf3\r\n' 
```
My platform is:
* Debian Testing
* neovim 0.2.2
* pandoc 2.1.1-1 amd64

 However, when I open the same `pandoc` file with `vim 8.0`, there's no such error.

**Comment by fmoralesc** [comment]
@nirvana6 This is a different issue. The problem is with our change from using python2/3 to python3 only. See https://github.com/vim-pandoc/vim-pandoc/issues/244 for a possible solution.

**Comment by nirvana6** [comment]
@fmoralesc  thank you. I solve my problem following your advice. Within `~/.vim/plugged/vim-pandoc` (where I install `vim-pandoc`): 
```shell
find . -name '__pycache__' -exec rm -r {} \; 
```
to delete all the `*.pyc` file. After this, no errors occur.
