### ISSUE TITLE
Support for vims (filename) placeholder syntax

### ISSUE THREAD

**Issue by bvolkmer** [vim-pandoc/vim-pandoc#258]
This plugin should allow (filename) placeholder.

I use this command most of the time, when using pandoc in vim:
`:!pandoc -o %:r.pdf %`
which will be interpreted by vim as the following (with file name `test.md`):
`pandoc -o test.pdf test.md`
`%` is placeholder for the full filename in buffer, and the additon `:r` removes the extension.

This is not possible with `:Pandoc` command of this plugin.

**Comment by fmoralesc** [comment]
It should be possible now ;)
