### ISSUE TITLE
Noob question - using pandoc folding for vimwiki files

### ISSUE THREAD

**Issue by abers** [vim-pandoc/vim-pandoc#260]
I have vimwiki set to use markdown over the default vimwiki syntax. I have managed to get syntax highlighting working when using vimwiki by adding the following line to my .vimrc:

`au FileType vimwiki set syntax=markdown.pandoc`

However, I have been unable to figure out how to get the pandoc folding to also apply in vimwiki.

**Comment by fmoralesc** [comment]
I think this should do the work:

```
au Filetype vimwiki call pandoc#folding#Init()
```

That function initializes the vim-pandoc folding module for the buffer.

**Comment by fmoralesc** [comment]
I think this should do the work:

```
au Filetype vimwiki call pandoc#folding#Init()
```

That function initializes the vim-pandoc folding module for the buffer.

**Comment by fmoralesc** [comment]
You can try with this
```
au Filetype vimwiki set foldmethod=expr | set foldexpr=pandoc#folding#FoldExpr()
```

**Comment by abers** [comment]
Right after some experimenting I realised that pandoc folding was no longer working for **any** markdown file. Turns out the vimwiki plugin is conflicting with it in some way. Adding `let g:vimwiki_global_ext= 0` fixed it for markdown files outside the vimwiki folder locations. There are variables for disabling folding in vimwiki or setting it to 'custom' which is supposed to let other plugins handle folding. However, neither setting fixed the issue.

**Comment by fmoralesc** [comment]
Ah, I see! I'll tag this as an external issue with a workaround, in case someone else has the same problem. Please link to this issue when you report the issue at vimwiki ;)

**Comment by abers** [comment]
Issue is available [here](https://github.com/vimwiki/vimwiki/issues/461). Basic markdown folding can be enabled still within vimwiki using `let g:vimwiki_folding='expr'` - however, that does not support YAML folding and its way of folding may differ from how folk have setup folding in vim-pandoc.
