### ISSUE TITLE
Vim immediately closes any markdown file

### ISSUE THREAD

**Issue by mpecon** [vim-pandoc/vim-pandoc#261]
I have a problem getting vim to link correctly to pandoc. It was working fine earlier but stopped working since a recent homebrew update. As soon as I open any markdown file (or setting filetype to markdown) the file is closed immediately. 

I have pandoc 2.1.2 installed on Mac OS 10.12, and my Vim version (compiled by homebrew is 8.0, 1-1522). I can run pandoc from the command line without problems.  

Can you advise what I need to do to fix this? Thank you for your help!

**Comment by fmoralesc** [comment]
Hi! What do you mean 'the file closes'? Does the buffer get deleted, or does vim crash? 

The only mayor recent change to vim-pandoc is that I dropped python2 support, and that can cause some issues, but I had never received reports of something quite as catastrophic happening :/ 

You say the file is closed if you set the filetype to markdown. Have you tried using the `pandoc` filetype directly?

**Comment by mpecon** [comment]
Thanks - when I type ":set filetype=pandoc", MacVim's current window crashes (but MacVim continues to stay open, as well as other MacVim windows). (When I then select "New Window", a new window appears but with ":buffers" empty.) Thanks again for your help!

**Comment by fmoralesc** [comment]
Hm... I think you are having this issue: https://github.com/vim-pandoc/vim-pandoc/issues/259 It seems like it is a macvim problem.

**Comment by fmoralesc** [comment]
You can check for some workarounds here: https://github.com/macvim-dev/macvim/issues/647

**Comment by mpecon** [comment]
Thanks so much. The workaround in [#259](https://github.com/vim-pandoc/vim-pandoc/issues/259) solved the issue (having confirmed that the :py3 command suggested in #259 led to the same error). It works beautifully now - thanks again!!!

**Comment by fmoralesc** [comment]
Great to hear!
