### ISSUE TITLE
Enable spell checking in `:` table captions

### ISSUE THREAD

**Issue by memeplex** [vim-pandoc/vim-pandoc#264]
When a table caption starts with just `:` instead of `Table:` spell checking is disabled for the caption.

**Comment by Konfekt** [comment]
This issue should be discussed in `vim-pandoc-syntax`. Please check if https://github.com/vim-pandoc/vim-pandoc-syntax/pull/267 solves your issue.

**Comment by alerque** [comment]
If not, please open an issue on that repository. It's a bit of a quirk of `vim`, but whether or not to spell check any given piece of input is left up to the syntax highlighter to allow checking or not. If this is an issue it should be raised on that repository, not this one. Thanks for understanding, and I hope that PR does help you.

**Comment by Konfekt** [comment]
Yes, there are good reasons for disabling spell checking in table headers, but I have no strong opinions thereon and am happy to help @memeplex

**Comment by alerque** [comment]
Sure I would see some too! But if in all the examples I can think of if the headers are a problem the cells are likely to be ever more of a problem, so erring on the side of potential usefulness seemed like the way to go.
