### ISSUE TITLE
Formatting save, unmap, restore... why?

### ISSUE THREAD

**Issue by memeplex** [vim-pandoc/vim-pandoc#267]
I'm getting a hard time understanding the behaviour of formatting.vim when it comes to setting the hard/soft modes:

* `UseHardWraps`:
    * Saves current j and k mappings
    * Unmaps j and k
    * Does things apparently unrelated to the j and k mappings
    * Restores j and k mappings

* `UseSoftWraps`:
    * Does nothing with the j and k mappings

Now, what I would have expected is something more like:

* `UseHardWraps`:
    * Restores user j and k mappings if needed

* `UseSoftWraps`:
    * Saves user j and k mappings
    * Conveniently map j and k to gj and gk

Besides, I'm unable to make sense of the complex sequence of save, unset, restore in `UseHardWraps`, which seems to me a contrived form of NOP (I mean, it seems to be doing nothing, to cancel itself).

What am I missing here?

**Comment by memeplex** [comment]
And a last question: are the `UseHard/SoftWraps` functions intended to switch modes on the fly? Or just to initialize the default mode of operation?

For example, a long time ago I wrote my own `SetWrap` function (see below) which I use for a number of different filetypes. Is it expected that I set `pandoc#formatting#mode` to, say, `'h'` and then use my `SetWrap` to switch between modes?

```
" Set wrap mode for current buffer (on, off, toggle)
function! SetWrap(mode)
    if a:mode == 'on' || (a:mode == 'toggle' && !&wrap)
        setlocal wrap linebreak
        let b:formatoptions = &l:formatoptions
        let b:colorcolumn = &l:colorcolumn
        let b:cursorline = &l:cursorline
        setlocal formatoptions-=t colorcolumn= nocursorline
        map <buffer> k gk
        map <buffer> j gj
    elseif a:mode == 'off' || (a:mode == 'toggle' && &wrap)
        setlocal nowrap
        let &l:formatoptions = b:formatoptions
        let &l:colorcolumn = b:colorcolumn
        let &l:cursorline = b:cursorline
        unmap <buffer> k
        unmap <buffer> j
    endif
endfunction
```

**Comment by fmoralesc** [comment]
I'm revisiting this. I don't even remember what was the rationale for the current behavior, and I agree with you.
