### ISSUE TITLE
disable folding insertleave autocmd's

### ISSUE THREAD

**Issue by Konfekt** [vim-pandoc/vim-pandoc#270]
The autocmd's in
```vim
    augroup EnableFastFolds
        au!
        autocmd InsertEnter <buffer> setlocal foldmethod=manual
        autocmd InsertLeave <buffer> setlocal foldmethod=expr
    augroup end
```
cause a huge lag when leaving insert mode in larger files. Please let the user decide on implementing them. If folding is slow, he might try my plug-in `FastFold`.

**Comment by fmoralesc** [comment]
In my tests this was always faster than not, but I didn't test in extremely large files. Would making this opt-out a good solution, do you think? (Of course, I would be happy yo point to your plugin in the documentation.)

**Comment by Konfekt** [comment]
Ok, that works. However, I think the best solution is opt-in, with a FAQ entry: 
```vim
Q: Folding is slow...
A: Get FastFold (https://github.com/Konfekt/FastFold) or add to ~/.vim/ftplugin/pandoc.vim the following lines:
    augroup EnableFastFolds
        au!
        autocmd InsertEnter <buffer> setlocal foldmethod=manual
        autocmd InsertLeave <buffer> setlocal foldmethod=expr
    augroup end
```
It lags over here if the markdown file has a couple of hundred lines.

**Comment by fmoralesc** [comment]
Hm. That is kind of weird: I've been working on a 1250 line file recently without problems. However, I use hard line breaks, and if you are using soft breaks, that might cause a difference (soft breaks have always felt laggy to me, regardless of folding).

**Comment by Konfekt** [comment]
Yes, over here http://rhodesmill.org/brandon/2012/one-sentence-per-line/ is adhered to.

The analogue issue was discussed at https://github.com/lervag/vimtex, too and the following solution found:

https://github.com/lervag/vimtex/blob/5734cdb2b82af0c9c57b211855d910cae0d0d4ca/doc/vimtex.txt#L1008

**Comment by Konfekt** [comment]
In the spirit of the discussion of https://github.com/vim-pandoc/vim-pandoc/issues/301 , could this be turned into a module that is enabled by default ?  (Which would be your preference, while I suggest disabling it by default as it is more of a hack which rears its dismal head at other ends such as #280)

**Comment by fmoralesc** [comment]
Hmm.. turning it into a module sounds like overkill to me. I think we can put it behind a flag, make it opt-in, and add some pointers to FastFolds in the FAQ.
