### ISSUE TITLE
error message: imp module deprecated in favour of importlib

### ISSUE THREAD

**Issue by mickmcq** [vim-pandoc/vim-pandoc#273]
Whenever I open a markdown file after upgrading python to 3.7, I see the following error:

```
Error detected while processing function pandoc#bibliographies#Init:
line   40:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see th
e module's documentation for alternative uses
```

It appears to refer to file `vim-pandoc/autoload/pandoc/bibliographies.vim` which has a function called `pandoc#bibliographies#init` and which contains a `py3 import` soon after line 40.

**Comment by fmoralesc** [comment]
What's weird for me is that we don't use `imp` or `importlib` ourselves. Are you using neovim? If you are, perhaps this is a problem with the python host.

**Comment by mickmcq** [comment]
Switching from macvim 8.1-149_1 to 8.0-145 banishes the error message. All other (intermediate) versions I tried failed to load at all.

**Comment by fmoralesc** [comment]
Maybe you got affected by something like https://github.com/vim-pandoc/vim-pandoc/issues/244 (so your python interpreter is trying to load incompatible .pyc files). The solution is to remove those.

**Comment by mickmcq** [comment]
I removed all the .pyc files and upgraded Vim to the latest version 8.1-149_1 and the issue did NOT reappear. Thanks!

**Comment by phlind** [comment]
I have the same issue. Where can I find those .pyc files to delete them? Thanks in advance.

**Comment by mickmcq** [comment]
I said

```{bash}
cd ~/.vim
find . -name "*.pyc"
```

and found the files in `vim-pandoc/python3/vim_pandoc/__pycache__/` and also in `vim-pandoc/python3/vim_pandoc/bib/__pycache__/`

but I have to admit that, although I thought that solved the problem, it really seems to not have solved the problem for me. I will probably reopen this after I investigate further.
