### ISSUE TITLE
Folding with Smart Autoformatting Causes Undo to Lag

### ISSUE THREAD

**Issue by keyofnight** [vim-pandoc/vim-pandoc#280]
I'm running vim 8.1.500, and have these options in `~/.vim/vimrc`:
```
let g:pandoc#formatting#mode = 'hA'
let g:pandoc#folding#fdc = 0
let g:pandoc#folding#mode = 'relative'
```
When I edit files of moderate length (500-1000 lines) with a few headings (5-10), and if I add a sentence to a paragraph and try to undo it, it takes a few seconds to complete the undo. When I disable folding (`let g:pandoc#modules#disabled = ["folding"]`) or smart auto-formatting (`let g:pandoc#formatting#mode = 'ha'`), undo works really fast.

With the help of the folks from #vim, I also found that changing foldmethod to manual before an undo operation makes it work quickly too. Right now, I have `u` mapped to my own undo function that changes the foldmethod right before/after undoing, but it's not ideal (as it makes a mess of my command history):
```
nnoremap u :call <sid>undo()<cr> 

function! s:undo() 
    let l:fdm = &foldmethod
    set foldmethod=manual
    undo     
    if &fdm
        let &foldmethod = l:fdm
    endif
endfunction
```
I have a feeling this is related to #270, but I'm not sure where to go from here.

**Comment by Konfekt** [comment]
Most probably it is related to #270. Please install FastFold, add
```vim
autocmd FileType pandoc 
      \ if exists('#EnableFastFolds') |
      \   autocmd! EnableFastFolds |
      \   augroup! EnableFastFolds |
      \ endif
```
to your `vimrc` and report on whether this has solved your lag.

**Comment by alerque** [comment]
This might be fixed by #303, @keyofnight are you able to update and confirm that this is fixed for you?

**Comment by keyofnight** [comment]
I've updated, installed fastfold, and the slowdown seems resolved. But, now: folding functionality has changed. Now, if I have two splits open, and I use `zc` to close a fold, the *next* fold opens, the current folds stays open, and I get an error saying `E490: No fold found.` If I close one of the splits, opening/closing fold works as expected.

I have the following in `vimrc`: 
```viml
autocmd FileType pandoc
      \ if exists('#EnableFastFolds') |
      \   autocmd! EnableFastFolds |
      \   augroup! EnableFastFolds |
      \ endif

let g:pandoc#formatting#mode = 'hA'
let g:pandoc#folding#fdc = 0
let g:pandoc#folding#mode = 'syntax'
let g:pandoc#folding#fastfolds = 1
```

**Comment by fmoralesc** [comment]
@keyofnight  Maybe try disabling vim-pandoc's fastfolds setting, it is possible that it doesn't behave well alongside the plugin (it is meant as a simpler built-in solution).

**Comment by Konfekt** [comment]
This conflicts. With `let g:pandoc#folding#fastfolds = 1` things will behave as before, whereas
```vim
autocmd FileType pandoc
      \ if exists('#EnableFastFolds') |
      \   autocmd! EnableFastFolds |
      \   augroup! EnableFastFolds |
      \ endif
```
ensures that things behave as if `g:pandoc#folding#fastfolds = 0`, the default.

**Comment by Konfekt** [comment]
The setting
```vim
autocmd FileType pandoc
      \ if exists('#EnableFastFolds') |
      \   autocmd! EnableFastFolds |
      \   augroup! EnableFastFolds |
      \ endif
```
has now become obsolete.

**Comment by fmoralesc** [comment]
@Konfekt it might be a good idea to add a module for integration with the FastFolds plugin to vim-pandoc-after.

**Comment by keyofnight** [comment]
> The setting
> 
> ```viml
> autocmd FileType pandoc
>       \ if exists('#EnableFastFolds') |
>       \   autocmd! EnableFastFolds |
>       \   augroup! EnableFastFolds |
>       \ endif
> ```
> 
> has now become obsolete.

I've removed this autocmd, and now I'm just using `g:pandoc#folding#fastfolds = 1`… but I'm still getting the same odd behavior (where `zc` refuses to recognize there are folds) with two windows pointing at the same buffer.

**Comment by Konfekt** [comment]
@keyofnight But if `g:pandoc#folding#fastfolds = 1`, then everything behaves as before, in particular, the odd behavior. Perhaps confusingly, `g:pandoc#folding#fastfolds = 0` (or omitting and defintion of `g:pandoc#folding#fastfolds`) applies the changes whereas `g:pandoc#folding#fastfolds = 1` undoes them.

**Comment by Konfekt** [comment]
@fmoralesc I am not sure what this module should do, other than ensuring that `g:pandoc#folding#fastfolds = 0`.

**Comment by keyofnight** [comment]
Oh. I see! Thanks for clarifying. Unfortunately, `zc` behaves oddly no matter what `g:pandoc#folding#fastfolds` is set to.

**Comment by fmoralesc** [comment]
@Konfect Yes, exactly that. It doesn't have to be clever. Just prevent the conflict.

**Comment by Konfekt** [comment]
@keyofnight Then you should give us the outputs of `:verb setlocal foldmethod?` and `:verb setlocal foldexpr?` to see if this relates to `vim-pandoc`.

**Comment by keyofnight** [comment]
@Konfekt The output of `:verb setlocal foldmethod?` is `foldmethod=manual`—set by `~/.vim/bundle/FastFold/plugin/fastfold.vim`.

The output of `:verb setlocal foldexpr?` is `foldexpr=pandoc#folding#FoldExpr()`—set by `~/.vim/bundle/vim-pandoc/autoload/pandoc/folding.vim`.

**Comment by fmoralesc** [comment]
I can confirm the problem.

I know what is causing it. vim-pandoc disables the computation of folds when a file is open in multiple windows/splits (it causes major lag otherwise). So when the fastfolds plugin is enabled, the existing folds seem to be cleared and then are not reset. In normal use without the fastfolds plugin, vim-pandoc will retain the existing folds but stop recalculating them.

I'm not sure what the best solution will be. Maybe we have to make [this part of the code](https://github.com/vim-pandoc/vim-pandoc/blob/master/autoload/pandoc/folding.vim#L110-L115) conditional on the value of `g:pandoc#folding#fastfolds`.

**Comment by fmoralesc** [comment]
Opened a PR with the suggested change (#306). Can you confirm that it solves the issue, @keyofnight?

**Comment by keyofnight** [comment]
The change (#306) seems to have fixed this issue. Thank you, and @Konfekt, for all of your diligence on this.
