### ISSUE TITLE
Cannot compile "Pandoc" (command missing --> E464)

### ISSUE THREAD

**Issue by daaronr** [vim-pandoc/vim-pandoc#288]
#81 (comment)
@fmoralesc

I'm having the same issue now that @SuperFluffy had, three years later. All was working until I installed Mojave (and simultaneously, installed markdown support for R/Rstudio).

Now, when I try to compile using the Pandoc tab (or with the command) I get the "E464: Ambiguous use" message.

I've reinstalled the latest version of Pandoc and Python (Python3).
Any advice would be greatly appreciated.

**Comment by daaronr** [comment]
Update:
After doing some things suggested by 'brew doctor' the error has changed.  It now throws

`Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yosemite/.vim/pythonx/vim_pandoc/command.py", line 282, in <module>
    pandoc = PandocCommand()
  File "/Users/yosemite/.vim/pythonx/vim_pandoc/command.py", line 115, in __init__
    self.opts = PandocHelpParser()
  File "/Users/yosemite/.vim/pythonx/vim_pandoc/command.py", line 16, in __init__
    self._help_data = Popen(["pandoc", "--help"], stdout=PIPE).communicate()[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined  `

**Comment by avinashpai** [comment]
Having a similar issue! Oddly enough when I used :Pandoc pdf earlier today it worked and now I am getting "E464: Ambiguous use" .

**Comment by fmoralesc** [comment]
@daaron, make sure to reinstall the plugin, for some reason it is trying to use python2 (this can happen when there are leftovers from previous installs).

**Comment by daaronr** [comment]
Thanks. it is now working on NeoVim (I switched) I don't want to tamper with anything at the moment, so I won't do a reinstall until necessary.

**Comment by alerque** [comment]
@daaronr Fair enough. It seems like this is probably resolved. If it ever turns out to be an issue again or anybody else seems this problem feel free to comment here and we'll get the issue reopened.

**Comment by daaronr** [comment]
It is happening again, even on NeoVim. I reinstalled the plugin and I'm getting the 'ambiguous command' again

**Comment by treuss** [comment]
Same here using Vim 8.2. Deleted all the `__pycache__`-folders, even uninstalled `vim-pandoc` and `vim-pandoc-syntax` completely. No chance to get it working again.
The only commands defined by `vim-pandoc` are: `PandocHighlight` and `PandocUnhighlight`

**Comment by daaronr** [comment]
(Fwiw one can probably add a command to the vimrc to do the same thing)
