### ISSUE TITLE
YouCompleteMe auto-completion

### ISSUE THREAD

**Issue by abers** [vim-pandoc/vim-pandoc#294]
I have having difficulty getting auto-completion with YouCompleteMe to work. If I am editing test.md with test.bib in the same folder typing @r followed by Ctrl+x and Ctrl+o works. Following the help tags for vim-pandoc I added the following to my vimrc (and restarted the YCM server):

```
if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers.tex = ['@']
```

However, nothing happens when typing a @. YCM works fine when editing python files. What am I doing wrong?

Running the YcmCompleter command provides the following error:

`ValueError: No semantic completer exists for filetypes: ['pandoc']`

Also tried adding the following to my vimrc to no avail:

```
let g:ycm_filetype_whitelist = {
       \ 'pandoc': 1,
       \ 'markdown': 1}
let g:ycm_filetype_blacklist = { 'tagbar': 1}
```

**Comment by abers** [comment]
Right finally fixed it. The helptags assume you are working with restructured text. To get autocompletion to work with pandoc markdown you need to add the following to your vimrc:

```
if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers.pandoc = ['@']
let g:ycm_filetype_whitelist = {
       \ 'pandoc': 1,
       \ 'markdown': 1}
let g:ycm_filetype_blacklist = {}
```

The blacklist can include what you want, but needs to clear out pandoc and markdown which are included by default.

**Comment by fmoralesc** [comment]
Added to the documentation.
