### ISSUE TITLE
No wordcount

### ISSUE THREAD

**Issue by NatalieGates** [vim-pandoc/vim-pandoc#296]
I am having a difficult time finding a word count solution. I would also like to use the `vim-airline` plugin which typically shows the word count by default on `md` and `txt` files. But since `vim-pandoc` changes the `md` to `pandoc` syntax I am unable to see a word count on my `md` files.

Can you help me resolve this?

**Comment by NatalieGates** [comment]
Sorry. The following line worked in my .vimrc file. I must have had a typo. Sincerely apologize for creating this issue.

`let g:airline#extensions#wordcount#filetypes = 'pandoc'`

**Comment by fmoralesc** [comment]
No worries ;)
