### ISSUE TITLE
How do you call Pandoc as part of another command

### ISSUE THREAD

**Issue by sdondley** [vim-pandoc/vim-pandoc#311]
I'm trying to figure out how to do something like this:

`command! PostBlog :Pandoc -o 'blog/' . expand('%')`

This just results in error about "invalid channels" and other errors depending on what I try. How can I achieve my intention?

**Comment by fmoralesc** [comment]
Can you post the errors you are getting? Are you using vim or nvim?

**Comment by fmoralesc** [comment]
I tried this out, and the problem is with how the filename is expanded. I'll try to fix it asap.

**Comment by sdondley** [comment]
I'm on neovim. In case you still need me error output:

```
Error detected while processing function pandoc#command#Pandoc[2]..provider#python3#Call:
line   18:
Invalid channel: 3
Error detected while processing function pandoc#command#Pandoc[5]..provider#python3#Call:
line   18:
Invalid channel: 3
```

Thanks!

**Comment by fmoralesc** [comment]
In general though, the Pandoc command swallows all the arguments, so it isn't really possible to use functions in calls to the commant. What you can do is wrap the Pandoc command into an execute command:
``` vim
command! Postblog execute "Pandoc -o 'blog/".expand('%')."'"
```

**Comment by sdondley** [comment]
Thanks. Just tried your suggestion but I'm still getting the same errors as above.

**Comment by sdondley** [comment]
Actually, it does work after closing out Vim and opening a new session (weird that renaming the command was't enough). Thanks for the hand!
