### ISSUE TITLE
NameError: name 'pandoc' is not defined

### ISSUE THREAD

**Issue by TriaSirax** [vim-pandoc/vim-pandoc#333]
Hi, I'm on linux kernel version 5.3.6. Using python 3.6.9 and neovim 0.4.2. It's my first time with pandoc and this plugin. When I try to convert some basic markdown to anything else. I get this error:

Error detected while processing function pandoc#command#Pandoc[2]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/triasirax/.config/nvim/plugs/vim-pandoc/python3/vim_pandoc/command.py", line 283, in <module>
    pandoc = PandocCommand()
  File "/home/triasirax/.config/nvim/plugs/vim-pandoc/python3/vim_pandoc/command.py", line 17, in __init__
    self.pandoc_info = PandocInfo(vim.vars["pandoc#command#path"])
  File "/home/triasirax/.config/nvim/plugs/vim-pandoc/python3/vim_pandoc/helpparser.py", line 16, in __init__
    self.update()
  File "/home/triasirax/.config/nvim/plugs/vim-pandoc/python3/vim_pandoc/helpparser.py", line 26, in update
    self.version = self.get_version()
  File "/home/triasirax/.config/nvim/plugs/vim-pandoc/python3/vim_pandoc/helpparser.py", line 38, in get_version
    return self.__raw_output('--version', pattern=versionPattern)
  File "/home/triasirax/.config/nvim/plugs/vim-pandoc/python3/vim_pandoc/helpparser.py", line 19, in __raw_output
    data = ensure_string(Popen([self.pandoc, cmd], stdout=PIPE).communicate()[0])
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pandoc': 'pandoc'
Error detected while processing function pandoc#command#Pandoc[4]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined

:echo has("python") and has("python3") return 1 by the way.

**Comment by fmoralesc** [comment]
It seems as if vim-pandoc couldn't find the pandoc executable, is it
available in the PATH that nvim can see? Can you check if `:!pandoc
--version` works?

**Comment by TriaSirax** [comment]
I guess you are right, it says command not found.

**Comment by fmoralesc** [comment]
You can add manually the path where pandoc is to your vimrc/init.vim, by
modifying the `PATH` environment variable. I'm away from my machine, and I
don't remember exactly what steps to take, so I recommend you to check that.

**Comment by TriaSirax** [comment]
Should I install pandoc separately? I thought it comes with the plugin, since it is not listed under requirements.

**Comment by fmoralesc** [comment]
Yes, it should be installed separately. I'll make a note to add it to the
requirements ;)

**Comment by TriaSirax** [comment]
Okey, my bad then. It will take forever to compile all that Haskell dependencies on gentoo :/ I thought the plugin comes with pre-compiled binary so that I could spare some time. Sorry

**Comment by fmoralesc** [comment]
No worries. I think you can get a precompiled binary from pandoc's website.
Recompiling all that Haskell *is* a pain... Which is why we don't
vendor/distribute it here.

**Comment by fmoralesc** [comment]
https://github.com/jgm/pandoc/releases/tag/2.7.3

**Comment by TriaSirax** [comment]
Thank you very much! It is working now. A little wiki on basics and syntax would be great though, like how can I specify a latex engine

**Comment by fmoralesc** [comment]
For pandoc's syntax and usage, the manual is excellent: https://pandoc.org/MANUAL.html#pandocs-markdown (I *don't* mean this in a RTFM way). 

For help on using the plugin itself, check `:help  pandoc` inside nvim. That describes all the nuts and bolts... It's a fairly extensive plugin, so there is a lot to check; but the most important things are in the COMMAND and SETTINGS sections.

**Comment by fmoralesc** [comment]
I forgot: if you need to produce PDFs, you'll need a LaTeX installation (check https://www.tug.org/texlive/quickinstall.html if you haven't)

**Comment by TriaSirax** [comment]
After installing a new cli program the first thing I do is RingTFM but since I'm new to vim I didn't know about the help command. And passing the arguments were pretty straightforward. Again thank you very much for your help and this amazing plugin.
