### ISSUE TITLE
Disable text transformations when pasting

### ISSUE THREAD

**Issue by gustavo-hms** [vim-pandoc/vim-pandoc#338]
Hi!

If I have `vim-pandoc` plugin enabled, and only if I have it enabled, whenever I paste some markdown text, a (markdown-equivalent) transformed version of the original text is inserted. For instance, if I have the following excerpt:

```markdown
# A topic

This is the content of this topic.

## A subitem

Just some more words.

# Another topic

[A link](a_link)
```
it is automatically changed to

```markdown
A topic
=======

This is the content of this topic.

A subitem
---------

Just some more words.

Another topic
=============

[A link]

  [A link]: a_link
```
when pasted in the buffer. How can I disable this behaviour?

**Comment by alerque** [comment]
Hmmm, there should be a preference to unset the `formatprg`. Or else something in vim to not auto reformat incoming pasts. Off the top of my head I can't remember but I think I set this up for another plugin that was doing this, I'll look sometime.

**Comment by gustavo-hms** [comment]
It's not clear, from your message, who is changing the text. Is it vim-pandoc? If so, doesn't the plugin itself provide an option to turn it off? If it doesn't, I thing it should. I couldn't find anything in the docs though.

By the way, my `formatprg` is empty so, probably, it isn't making any difference in this behaviour.

**Comment by alerque** [comment]
I am unable to replicate this behavior at all. Are you sure you don't have some other plugin triginging something on paste?

**Comment by gustavo-hms** [comment]
Ok, I found it! When disabling the other plugins I use, I've forgotten one of them: [easyclip](https://github.com/svermeulen/vim-easyclip). It has an option (`g:EasyClipAutoFormat`) that was enabled in my configuration and caused this behaviour. Strangely enough, it only edited the pasted text if `vim-pandoc` was enabled (it leaves the text unchanged otherwise) and, as such, makes me do a wrong diagnostic.

Thank you anyway for the attention and sorry for not making a careful test before opening the issue.

**Comment by alerque** [comment]
Sounds like it was (correctly) detecting something this plug-in  sets in regard to reformatting options — and perhaps not doing much of anything when such settings were not detected. I'm a bit confused why your `formatprg` is blank, but glad you found the source of unwanted behavior. You might look into adding Pandoc options that actually format your markdown the way you want it!
