### ISSUE TITLE
:TOC produces an error since last update

### ISSUE THREAD

**Issue by jeepyoudin** [vim-pandoc/vim-pandoc#339]
Since the last update, I am been having a pblm with :TOC with all my PCs. Everything was working fine before the plugin update.

I received an error message:
**Error detected while processing function pandoc#toc#Show[25]..pandoc#toc#ReDisplay:**
line10
**E119: Not enough arguments for function: substitute**
Press ENTER or type command to continue

and now the "TOC window" shows this for each (sub)section : 
_/home/jpo/jpottt3.md|30 col 1| ## Sub Section¬_ 
not the usual presentation...
Do you have an idea ?

**Comment by fmoralesc** [comment]
This should be fixed by #337.

**Comment by alerque** [comment]
Oops, that PR got held up because I was going to review it. And didn't.

**Comment by jeepyoudin** [comment]
#337 fixed it , like you said. Thanks !

**Comment by fmoralesc** [comment]
We might do something a little different for the final solution there, @jeepyoudin, but it should be solved properly soon ;)

**Comment by alerque** [comment]
I went ahead and merged that fix because I can't find how to do it better at the moment and there is no point in more people running across this breakage while I work that out.
