### ISSUE TITLE
Is there any way to disable vim-pandoc folding entirely?

### ISSUE THREAD

**Issue by kctong529** [vim-pandoc/vim-pandoc#344]
I already had a set of folding rules based on indent globally set in `~/.vimrc`, but when I tried to use vim-pandoc, I discovered `setlocal foldmethod=expr` inside of `function! pandoc#folding#Init()` in `vim-pandoc/autoload/pandoc/folding.vim`.

While I appreciate other aspects of the plugin, I prefer indentation folding, and having to set `foldmethod` every time when I open a new markdown file is not cool at all. Any suggestion?

**Comment by kctong529** [comment]
`:call pandoc#folding#Disable()` does not change the behavior of it performing `:setlocal foldmethod=expr` every now and then (for example, when I switch to normal mode from insert mode).

**Comment by fmoralesc** [comment]
You can blacklist the folding module, that should disable everything:
``` vim
let g:pandoc#modules#disabled = ['folding']
```

**Comment by kctong529** [comment]
> You can blacklist the folding module, that should disable everything:
> 
> ```viml
> let g:pandoc#modules#disabled = ['folding']
> ```

Thanks for your help. It works!
