### ISSUE TITLE
move filetype detect part to `ftdetect/pandoc.vim`?

### ISSUE THREAD

**Issue by Freed-Wu** [vim-pandoc/vim-pandoc#349]
I recommend move filetype detect part to `ftdetect/pandoc.vim`.
```
    au BufNewFile,BufRead,BufFilePost *.pandoc,*.pdk,*.pd,*.pdc set filetype=pandoc
    if g:pandoc#filetypes#pandoc_markdown == 1
        " skip loading of /markdown/ftplugin.vim
        au BufNewFile,BufRead,BufFilePost *.markdown,*.mdown,*.mkd,*.mkdn,*.mdwn,*.md
                    \ let b:did_ftplugin=1 | setlocal filetype=pandoc
    endif
```
Because if users use plugin manger to lazy load this plugin, such as follow:
```
" load this plugin when set ft=markdown...etc
	call dein#add('vim-pandoc/vim-pandoc', {
				\ 'on_ft': ['pandoc', 'markdown', 'rst', 'textile', 'gfimarkdown'],
				\ })
```
the `plugin/pandoc.vim` will not be loaded before set ft. so whatever g:pandoc#filetypes#pandoc_markdown is 1 or 0, the 1st open `*.md` its filetype is always  markdown(the autocmd which set ft=pandoc is not loaded)
The reasonable solution is use ftdetect method. You can `:help ftdetect` to see more.
This is a suggestion, not very serious problem for this splendid plugin.
Thank you!

**Comment by alerque** [comment]
You're right, this would help some plugin managers ... and rightly so. I started moving this over in #352.

It does bring up some concerns that are going to need review about how and when we set user preference variables. I think we'll need to move the logic for setting `g:pandoc#filetypes#pandoc_markdown` if it doesn't exist into the ftdetect module as well.

**Comment by wookayin** [comment]
The ftdetect feature was working well for a long time, but somehow on recent versions of vim (or with other changes) it stopped working. Not sure why the autocmd statements are not executed. After checking out the `ftdetect` branch, ftdetect works well. I encourage this feature to be merged onto the master ASAP.
