### ISSUE TITLE
How do I properly remap named `<Plug>` mappings?

### ISSUE THREAD

**Issue by joelostblom** [vim-pandoc/vim-pandoc#356]
I have blacklisted the mappings for the 'links' module, because some of them interfere with my custom mappings. I want to add back a mapping for opening links in the same buffer, which I thought I could simply do like this:

    noremap <leader><CR> <Plug>(pandoc-keyboard-links-open)

However, seemingly nothing happens when I press that key combo. If I instead directly add [the function that the `<Plug>` mapping invokes](https://github.com/vim-pandoc/vim-pandoc/blob/6307e78e2f1729e37b82480f97b6e0e421e6e687/autoload/pandoc/keyboard/links.vim#L4), pressing the key combo follows links as expected.

    noremap <leader><CR> :call pandoc#hypertext#OpenLink( g:pandoc#hypertext#edit_open_cmd )<cr>

Is this how I am supposed to remap `<Plug>` mappings, or am I just missing something in my first attempt above?

**Comment by hupfdule** [comment]
That's because Plug-mappings _need_ recursive mapping in vim.

Therefore use `noremap <leader><CR> <Plug>(pandoc-keyboard-links-open)` instead.

**Comment by alerque** [comment]
Thanks for pointing that out @hupfdule.
