### ISSUE TITLE
Support vim filename placeholder in templates

### ISSUE THREAD

**Issue by bertin0** [vim-pandoc/vim-pandoc#371]
Issue #258 and subsequent commit  2e342ac  added support for vim's placeholders for filename (%, %:r) in the :Pandoc command, but a template made containing it doesn't work.

For example: 
```
:Pandoc html5 -o Outputs/%:r.html
```
correctly expands the filename, but saving it as a template and running the template
```
:PandocTemplate save test
:Pandoc #test
```
produces the file `Outputs/:%r.html`

**Comment by alerque** [comment]
Thanks for pointing this out! We'd love a PR that fixes this if anybody wants to take it on.
