### ISSUE TITLE
Pandoc converting error in Vim

### ISSUE THREAD

**Issue by Remiol** [vim-pandoc/vim-pandoc#375]
Hi,

I installed today the latest pandoc (pandoc-2.9.2.1-windows-x86_64.msi)
and vim-pandoc
and vim-pandoc-syntax
(vim 8.1)

I created a markdown file test.pandoc in vim

When I use the command

> :Pandoc (or Pandoc docx)

I receive this error:

```
Error detected while processing function pandoc#command#Pandoc:
line 2:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "bundle\vim-pandoc\python3\vim_pandoc\command.py", line 284, in <module>
pandoc = PandocCommandO
File "bundle\vim-pandoc\python3\vim_pandoc\command.py", line 17, in __init__
self.pandoc_info = Pandoclnfo(vim.vars["pandoc#command#path"])
File "bundle\vim-pandoc\python3\vim_pandoc\helpparser. py", line 16, in __init__
self.update()
File "bundle\vim-pandoc\python3\vim_pandoc\helpparser.py", line 26, in update
self.version = self.get_version()
File "bundle\vim-pandoc\python3\vim_pandoc\helpparser.py", line 38, in get_version
return self.__raw_output('—version', pattern=versionPattern)
File "bundle\vim-pandoc\python3\vim_pandoc\helpparser.py", line 19, in __raw_output
data = ensure_string(Popen([self.pandoc, cmd], stdout=PIPE).communicate()[0])
File "C:\Python38\Lib\subprocess.py", line 854, in __init__
self._execute_child(args, executable, preexec_fn, close_fds.
File "C:\Python38\Lib\subprocess.py", line 1307, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

What did I wrong?

**Comment by alerque** [comment]
This looks like a problem with your PATH. Not being on Windows its pretty hard for me to debug, but you could try and make sure running `pandoc.exe` from the command line before you run vim actually works. Somehow whatever executable name vim-pandoc is guessing it should run is not actually being found by the system.

You may need to either fix where it is installed or adjust your PATH so that it can be run, or manually specify the full path to the executable in your vim config.

**Comment by Remiol** [comment]
Yes it was my path! Thank you very much. 
I'm new to pandoc and vim-pandoc. 

Still problems aver using `:Pandoc pdf`: 

```
Error reading bibliography
Error running filter pandoc-citeproc:
Filter returned error status 1
```
I read the manual better yesterday. 
Could not find an example of a bibliography file.
Do you know how to create a bibliography file?

**Comment by fmoralesc** [comment]
For bibliographies, http://www.jabref.org/ is good, although probably any software like Zotero and Mendeley will also produce bibliography files in a format that `pandoc-citeproc` can read.

I wonder why you are getting that issue, though, it seems like `vim-pandoc` detected a bibliography file and passed it to pandoc, but that file was not correctly read by `pandoc-citeproc`. Do you have any `*.bib` files in the current folder?

**Comment by Remiol** [comment]
Yes, you're right. Vim-pandec found a .json file in another directory. 
The file was used in another software.

Btw, why does vim-pandoc need a bibliography file if the command `!pandoc test.md --pdf-engine=pdflatex -o test.pdf` works fine?

**Comment by fmoralesc** [comment]
`pandoc-citeproc` supports having `.json` files a bibliography sources, so `vim-pandoc` defaults to treating those as such (it creates a list of possible bibliography sources every time you open the file). Maybe `json` files shouldn't be treated this way.

**Comment by fmoralesc** [comment]
The relevant line in the source is: https://github.com/vim-pandoc/vim-pandoc/blob/master/python3/vim_pandoc/bib/collator.py#L10

**Comment by Remiol** [comment]
Yes! I removed .json from this file.
Added a bibliography with just an Author name and Title and added the bibliography to the command `--bibliography="path"

It created my pdf file! Thanks!

Is it possible to preview the pandoc markdown in the browser as `markdown-preview.nvim` does for not-pandoc markdown code?

**Comment by alerque** [comment]
@Remiol This plugin doesn't currently provide any kind of preview function. You could hack a poor-man's version together with a `autocmd` that converted to HTML via Pandoc on save (or buffer changes, *ala* autosave) and a browser plugin that auto updated on file changes. Personally I don't think this plugin _should_ attempt to do what *markdown-preview.nvim* is doing, if anything that plugin could be tweaked to optionally use Pandoc to render HTML.

You could open a separate issue to track that feature request (even if we don't implement it directly it would still be useful to track for how it can be achieved via integration with some other plugin), but as it isn't related to this one I'm going to close this as resolved.
