### ISSUE TITLE
Bibliography completion

### ISSUE THREAD

**Issue by twsh** [vim-pandoc/vim-pandoc#377]
Bibliography completion used to work for me, but it recently stopped working and I'm finding it hard to work out what went wrong.

I have vim-pandoc installed. I have this in my .vimrc: `let g:pandoc#biblio#sources = "l"`. I have a bib file exported from Zotero in '$HOME/.pandoc/' called 'default.bib'. When I start typing a cite key and hit CTRL-X CTRL-O while in insert mode I get '-- Omni completion (^O^N^P) Pattern not found'.

I'm using Vim 8.1.1401 from the command line on Ubuntu 19.10. `:python3 import sys; print(sys.version)` returns '3.7.5 (default, Apr 19 2020, 20:18:17)'. I assume that means that I have Python support for my Vim (I think that I should have).

Is there something that I should try to work out what's going on? Thanks.

**Comment by fmoralesc** [comment]
@twsh Maybe the pycache files are stale from a previous version? () I haven't used the bibliography completion in a while (my current setup is not supported, ironically :p), but I also haven't changed anything in the system that could have caused a regression.

**Comment by twsh** [comment]
@fmoralesc Where might the pycahe files be? I just did a PluginClean/PluginInstall of vim-pandoc, so I should have the latest version with nothing hanging around in ~/.vim/bundle.

**Comment by fmoralesc** [comment]
Inside the `python3/vim_pandoc` folder. Those files are not tracked by git, so sometimes they linger after reinstalls. The issue might be related to #288

**Comment by twsh** [comment]
@fmoralesc I deleted __pycache__ from ~/.vim/bundle/vim-pandoc/python3/vim_pandoc and ~/.vim/bundle/vim-pandoc/python3/vim_pandoc/bib but it hasn't helped. Maybe when I update to Ubuntu 20.04 this will magically fix itself? Otherwise I will look at it again.

**Comment by twsh** [comment]
@fmoralesc So, I installed vim-gtk3 and the completion works there. Just not when I use vim in the terminal. I have no idea why.

**Comment by fmoralesc** [comment]
That is really weird. Does vim-gtk detect the same python version?

**Comment by twsh** [comment]
@fmoralesc  Yes, it says:

'3.7.5 (default, Apr 19 2020, 20:18:17)
[GCC 9.2.1 20191008] '

**Comment by emeralit** [comment]
Something happened after the last commit:

**Errore/i eseguendo function pandoc#bibliographies#Init[40]..provider#python3#Call:
riga   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mimmo/.local/share/nvim/plugged/vim-pandoc/python3/vim_pandoc/bib/vim_completer.py", line 4, in <module>
    from vim_pandoc.bib.collator import SourceCollator
  File "/Users/mimmo/.local/share/nvim/plugged/vim-pandoc/python3/vim_pandoc/bib/collator.py", line 68
    if (ext := os.path.splitext(f)[1]) != '' and ext[1:] in bib_extensions]
            ^
SyntaxError: invalid syntax**

**Comment by fmoralesc** [comment]
Yeah, that's my bad :p I went nuts with python 3.8 syntax (I'm guessing your python is 3.7, like @twsh). I will push a fix in a bit.

**Comment by fmoralesc** [comment]
@emeralit Should be fixed now.

**Comment by emeralit** [comment]
@fmoralesc Thanks you. Fixed.

**Comment by twsh** [comment]
I updated and now it's not working anywhere. I have tried adding the bibliography with `g:pandoc#biblio#bibs` in my .vimrc, and putting the bibliography in the same directory as the markdown file (with the same title).

I can only assume that it's some strange interaction between my Python and Vim setup, but I don't know how to investigate further.

**Comment by ruedigerblock** [comment]
Moin @twsh,
I had the same problem and tried hundreds of things and in the end it worked after I removed the vimwiki - Plugin which I had installed. Do use it or something similar ?

**Comment by twsh** [comment]
@ruedigerblock I did have vimwiki installed, although I have uninstalled it. These are the plugins I have now:

```
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax'
Plugin 'vim-pandoc/vim-pandoc-after'
Plugin 'KeitaNakamura/tex-conceal.vim'
```
I tried uninstalling tex-conceal, but that didn't help.

**Comment by fmoralesc** [comment]
@twsh Sorry for the late reply. Can you try checking what is the output of

``` vim
echo pandoc#bibliographies#Find_Bibliographies()
```
It should be a list of the files that pandoc will try to get bibliographical data from. If it's empty, then the problem is with how vim-pandoc is detecting the sources. If it isn't, then there's a problem parsing your bibliography files.

**Comment by twsh** [comment]
@fmoralesc No worries!

The output is '['/home/t/.pandoc/default.bib']'.

By the way, I have `let g:pandoc#biblio#sources = "cl"` in my .vimrc. I tried this with a file in a directory with no .bib files. So, I think the result is what should be expected.

**Comment by fmoralesc** [comment]
That narrows down things. Have you tried switching the completion source mode from the default to `citeproc`?

``` vim
let g:pandoc#completion#bib#mode='citeproc'
```

**Comment by twsh** [comment]
@fmoralesc I tried that now and nothing changed.

**Comment by emeralit** [comment]
> Moin @twsh,
> I had the same problem and tried hundreds of things and in the end it worked after I removed the vimwiki - Plugin which I had installed. Do use it or something similar ?

vimwiki plugin is the culprit for me too

**Comment by ivanvgav** [comment]
Hello, I have the same problem. I've installed vim-pandoc and vim-pandoc-syntax and also vimwiki with vim-zettel.

After I `echo pandoc#bibliographies#Find_Bibliographies()` it give me this:

```
Error detected while processing function pandoc#bibliographies#Find_Bibliographies[2]..provider#python3#Call:
line   18:
Error invoking 'python_eval' on channel 3 (python3-script-host):
error caught in request handler 'python_eval ['vim_pandoc.bib.vim_completer.find_bibfiles()']':
Traceback (most recent call last):
  File "/home/ivanvg/.local/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 169, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'vim_pandoc' is not defined

```

My settings are:

```
" Pandoc
	au FileType vimwiki call pandoc#completion#Init()
	let g:vimwiki_filetypes = ['pandoc', 'markdown', 'textile']
	let g:vimwiki_folding = 'custom'
	let g:pandoc#folding#fdc = 0
	let g:pandoc#folding#level = 999
	let g:pandoc#folding#mode = 'stacked'
	let g:pandoc#modules#enabled = ['folding', 'command']
	let g:pandoc#biblio#sources = 'gy'
	let g:pandoc#biblio#use_bibtool = 1
	let g:pandoc#completion#bib#mode = 'citeproc'
	let g:pandoc#biblio#bibs = ['Documents/biblio.bib']
" Pandoc Autocomplete
" enable ncm2 for all buffers
    autocmd BufEnter * call ncm2#enable_for_buffer()
    set completeopt=noinsert,menuone,noselect
augroup my_cm_setup
    autocmd!
    autocmd BufEnter * call ncm2#enable_for_buffer()
    autocmd Filetype pandoc call ncm2#register_source({
      \ 'name': 'pandoc',
      \ 'priority': 8,
      \ 'scope': ['pandoc'],
      \ 'mark': 'md',
      \ 'word_pattern': '\w+',
      \ 'complete_pattern': ['@'],
      \ 'on_complete': ['ncm2#on_complete#omni', 'pandoc#completion#Complete'],
      \ })
augroup END

```

Thanks in advance

**Comment by elzinus** [comment]
> > Moin @twsh,
> > I had the same problem and tried hundreds of things and in the end it worked after I removed the vimwiki - Plugin which I had installed. Do use it or something similar ?
> 
> vimwiki plugin is the culprit for me too

I seem to have the same issue. Everything is OK but omni complete just does not find anything.
Does anyone have an idea why vimwiki blocks working with bibliographies and omni completion in vim-pandoc?

Kind regards.

**Comment by twsh** [comment]
Unfortunately, updating to Ubuntu 20.04 did not fix it.

You mentioned that there is a possibility that there is a problem parsing my bib file. Is there something I can do to diagnose that? I exported it from Zotero using better biblatex.

**Comment by emeralit** [comment]
@twsh You can try to read this thread https://tex.stackexchange.com/questions/173621/how-to-validate-check-a-biblatex-bib-file

**Comment by twsh** [comment]
@emeralit Thanks. I'm pretty sure that there is nothing very wrong with the biblatex that Zotero exports. Checking with biber doesn't show anything up.

**Comment by emeralit** [comment]
Interesting thread here https://github.com/vimwiki/vimwiki/issues/461. 
Maybe it's time to get rid of vimwiki.

**Comment by SanD94** [comment]
@twsh I'm trying to setup vim-zettel and vim-pandoc together. So far, I have no problem when using the bibliography completion. Since I'm using lazy loading for plugins, I've added some pandoc configs to a file named `vimwiki.vim` to `after/ftplugin/`

```
call pandoc#completion#Init()
call deoplete#custom#var('omni', 'input_patterns', {
      \ 'vimwiki': '@'
      \})
```

Although the setup works well, it seems it may not help you at all.

**Comment by twsh** [comment]
I'm closing this because I think it's probably something specific to my setup and not a general issue. Thanks everybody.

By the way, bibliography completion works perfectly with [NeoVim](https://neovim.io/) for me.

**Comment by Ratramnus** [comment]
Dear @twsh,

Did you ever figure out a solution to this problem? I have the same problem, and cannot seem to solve it.

**Comment by twsh** [comment]
@Ratramnus No, the last time I checked I had the same issue. The only solution I found is that [Neovim](https://neovim.io/) works fine.

**Comment by Ratramnus** [comment]
@twsh, thank you for letting me know. I have the unfortunate problem that both Vim and Neovim have the same problem. Is your init.vim identical to your .vimrc?

**Comment by twsh** [comment]
@Ratramnus Yes, except that I have `let g:pandoc#biblio#sources = "l"` in my init.vim and I removed it from my .vimrc once I gave up on getting completion to work there. I am using 0.4.4 by the way, because that's what's in Ubuntu 21.10.

**Comment by Ratramnus** [comment]
@twsh thanks for your explanation. Alas, neovim still functions just as vim does. One more question, if I may: what version of python3 are you using? I suspect things changed for me with a new version of python3 (3.10).

**Comment by Ratramnus** [comment]
@twsh, I found the culprit line in my .vimrc:

autocmd BufNewFile,BufRead *.md set filetype=markdown

Once I deleted it, it fixed the problem. This is very strange, because I've had that in my .vimrc for a very long time, and then one day things just stopped working. Weird.

**Comment by twsh** [comment]
@Ratramnus I have Python 3.9.7. I had that line in both my .vimrc and init.vim. Taking it out fixes the problem with Vim, but didn't cause it with Neovim, for me. Thanks for the suggestion!

**Comment by Ratramnus** [comment]
@twsh (and @fmoralesc might be interested), the plot thickens!

I discovered that (on Linux) if **filetype=pandoc** (in ~/.vimrc) the bibliography completion will work. But if **filetype=markdown** it will not.

However, on MacOS no matter what the filetype is, I can't get bibliography completion to work. I do wonder if it has something to do with versions of python3 later than 3.8 (e.g. python@3.9 or @3.10)?
