### ISSUE TITLE
Accidental Auto-Completion When Using Omni-Completion

### ISSUE THREAD

**Issue by TheCedarPrince** [vim-pandoc/vim-pandoc#381]
I am not sure if this is an error or my inexperience with `vim-pandoc`.

When I type `@` and then have the omni-completion men pop up, the omni-completion window automatically completes to the first citation key that occurs in the menu. Any idea as to why this is? Here is a gif displaying the issue:

![vim_error](https://user-images.githubusercontent.com/29561456/86032116-dab2ae00-ba04-11ea-9403-2325dff1d7a5.gif)

How do I work around the issue? Thanks!

**Comment by alerque** [comment]
What completion interface are you using? I think this only provides a data source not an actual completion UI and this looks like an issue with the completion UI.

**Comment by TheCedarPrince** [comment]
@alerque - you are absolutely correct. I did not have deoplete set up properly. Thank you for your kindness and patience! Closing the issue. :smile:
