### ISSUE TITLE
--standalone in a template

### ISSUE THREAD

**Issue by twsh** [vim-pandoc/vim-pandoc#391]
If I do `:Pandoc! --standalone` I get what I would expect: an HTML file where my YAML metadata appears as a title.

If I save that template, e.g., `:PandocTemplate save test` and then do `:Pandoc! test` I get different output without the metadata. It seems that the --standalone option is being ignored. Is there some reason why I can't set it, or set it like that? I tried -s too.

My markdown:

```
---
title: Test
---

# Section

Some text
```

`PandocTemplate get test` returns '--standalone'.

**Comment by fmoralesc** [comment]
Are you using the `#` to use the template, as in `:Pandoc! #test`. It seems to work fine in a  quick test.

**Comment by twsh** [comment]
@fmoralesc No, I wasn't. My mistake.
