### ISSUE TITLE
Math block delimiters ($$) shouldn't be concealed to nothing

### ISSUE THREAD

**Issue by dkasak** [vim-pandoc/vim-pandoc#393]
Unless I'm having an interaction from another plugin, the math block delimiters (double dollar signs, `$$`) are concealed to an empty string. This is disorienting and makes it hard to navigate into an open but empty math block. I often enter `$$\n\n$$`, then exit insert mode and want to move inside the math block I just created, but since the dollar signs are invisible, I don't know whether my cursor is inside or not.

The proposal is then not to conceal the dollar signs or to conceal them into a more appropriate symbol instead of the empty string (unless I landed on a weird interaction with another plugin of mine).

**Comment by Konfekt** [comment]
This is a valid suggestion, though, for example [vimtex](https://github.com/lervag/vimtex/) does as pandoc.
In any event, as a syntax question, it is best posed over at [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax/)

**Comment by dkasak** [comment]
I'll open an issue in vim-pandoc-syntax then.
