### ISSUE TITLE
Changing pandoc#command#autoexec_command according to filetype

### ISSUE THREAD

**Issue by manolomartinez** [vim-pandoc/vim-pandoc#398]
Hello,

I was trying to find a way to make `pandoc#command#autoexec_command` behave differently if I'm working on a slideshow or an article, both in pandoc's markdown.

I was thinking of adding something like this to my `~/.vimrc`:

    autocm FileType beamer let g:pandoc#command#autoexec_command = "Pandoc beamer -i --filter pandoc-citeproc --number-sections"
    autocm FileType pandoc let g:pandoc#command#autoexec_command = "Pandoc pdf -i --filter pandoc-citeproc --number-sections"

Together with the relevant changes in `plugin/pandoc.vim` and adding a `ftplugin/beamer.vim` file. Ideally the beamer filetype would be indistinguishable from the pandoc one, except for my being able to use another autoexec command. 

Does this make sense? Is there an easier way to do this that I have overlooked?

**Comment by fmoralesc** [comment]
Hi! Makes total sense.

The only change needed for this is to put in place a `ftplugin/beamer.vim` file that sources `ftplugin/pandoc.vim`. Then you could do exactly what you are thinking with the snippet. This is essentially what the `ftplugin/rmarkdown.vim` file does [here](https://github.com/vim-pandoc/vim-rmarkdown/blob/master/ftplugin/rmarkdown.vim).

**Comment by manolomartinez** [comment]
Great :) It should be something like [this](https://github.com/vim-pandoc/vim-pandoc/pull/399), right? This doesn't load syntax highlighting in files with `beamer` filetype, though. What am I missing?

**Comment by fmoralesc** [comment]
Ahh, of course! There should also be a stub syntax/beamer.vim file that loads the pandoc syntax file (same idea as with the ftplugin file).

**Comment by manolomartinez** [comment]
Gotcha! Thanks for merging my `vim-pandoc-syntax`PR :) I've just submitted the complementary one for `vim-pandoc`. Do let me know if I need to change anything. Gracias por tu ayuda, Felipe.
