### ISSUE TITLE
Could not fetch resource imgs/image_name.png: replacing image with description

### ISSUE THREAD

**Issue by silver978** [vim-pandoc/vim-pandoc#426]
I am trying to convert a .md file with images inside in .pdf.

I run the `:Pandoc pdf` command and the .pdf file is created correctly, but Pandoc can't load images in it, even if the images' paths are correct.

![image](https://user-images.githubusercontent.com/24396955/161036660-642b990d-8a47-41c1-9913-c0d5057749ea.png)

Usually, I use VSCode to write markdown and I use the command `pandoc -f markdown-implicit_figures -t pdf my_file.md -o my_file.pdf` to create the .pdf: all the images are loaded correctly.

My .md files are on iCloud, but I am using the `:Pandoc pdf` command when I have one of them already opened in nvim.

How can I resolve this problem? Furthermore, how can I reproduce the command I use in VSCode into nvim (for the `-f markdown-implicit_figures` argument)?

If you need more information, let me know. Thank you in advance.

**Comment by jfab-123** [comment]
@silver978 How did you manage to solve this issue?

**Comment by silver978** [comment]
> @silver978 How did you manage to solve this issue?

Unfortunately, I didn't solve it, but I found a workaround.
If I understood correctly, the problem here are spaces in the path of images, which are not loaded correctly because of this: with my workflow, I can't avoid having these spaces.
So, I added this to my init.vim (or .vimrc):

```
nnoremap <C-e><C-p> :!pandoc -t pdf '%' -o '%:r'.pdf "--from=markdown-implicit_figures+rebase_relative_paths"<CR>

Running this command with the correct working directory set and your markdown file opened, its pdf version will be created in the same folder.

Hope that this helped, I am here for more info. 🙂
