### ISSUE TITLE
Image location bug. 

### ISSUE THREAD

**Issue by jfab-123** [vim-pandoc/vim-pandoc#429]
Suppose I have a project ```test.md``` located in ```~/Desktop```. In there I have a directory called ```~/Desktop/figures``` in which all my images are located. 

Let's say I open the file from the terminal ```nvim Desktop/test.md``` and it looks like this: 
```pandoc
# Test section

Test text. 

![Test figure](figures/test.png)
```

When I do ```:Pandoc pdf``` I get the following error: 
```[WARNING] Could not fetch resource figures/test.png: replacing image with description```. 

However, if instead of opening the file from ```~``` I do ```cd Desktop``` and then ```nvim test.md```,  when I try to compile the pdf I get no errors. 

The problem is that vim-pandoc doesn't run the command from the directory in which the file is located but from the location you opened the file. So in the first case it doesn't recognize ```figures/test.png``` because there is no such directory in ```~```.

**Comment by alerque** [comment]
This plugin assumes your CWD is where your file is, or at least relative to your project's root. You can change the directory after you start to you know... `nvim Desktop/test.md`, then inside vim run `:cd Desktop`.

I'm not sure this is a bug so much as a design choice. We would have to do quite a lot of brittle path probing and trial an error to guess anything better and that is likely to disturb more use cases than the one it might solve.

**Comment by alerque** [comment]
Also this is really a `pandoc` limitation and they have made the same design choice. I think we'll stick with assuming the user needs to `cd` to their project root just like they would if running `pandoc` directly.
